
<?php $barcode = Mage::getModel('simibarcode/simibarcode')->load($barcodeId); ?>
<?php $product = Mage::getModel('catalog/product')->load($barcode->getProductEntityId()); ?>
<div id="imageOutput" style="font-family: Segoe UI,Calibri,Arial,Helvetica; font-size:12px; margin:0; padding:0; float:left; text-align:left; width:100%" >
    <?php for ($i = 0; $i < $qty; $i++): ?>
        <?php if ($barcodeTemplate == 1): ?>
            <span style="display:block; width:100%; font-size:12px; text-align:left;"><?php echo ' '?></span>
            <img style="margin:5px 0" width="<?php echo $imageWidth ?>" name="barcode_images" src="<?php echo $imageUrl ?>" />

        <?php endif; ?>
        <?php if ($barcodeTemplate == 2): ?>
            <div style="width: <?php echo $imageWidth+10?>px; padding:5px; float:left">
                <span style="display:block;  font-size:11px; text-align:left; float:left;"><?php echo $barcode->getProductName() ?></span>

                <img style="float:left; margin-left:-9px" name="barcode_images" src="<?php echo $imageUrl ?>" />
            </div>
        <?php endif; ?>
        <?php if ($barcodeTemplate == 3): ?>
            <div style="width: <?php echo $imageWidth+10?>px; text-align: left; display:block; overflow: hidden;vertical-align: middle; float:left; padding:5px">
                <span style="float:left; font-size:11px; text-align:left; width:70%;"><?php echo $product->getName() ?></span>
                <span style="font-size: 12px; float: left; text-align: right; font-weight:bold;"><?php echo Mage::helper('core')->currency($product->getPrice()) ?></span>
            <img style="margin-left:-9px" name="barcode_images" src="<?php echo $imageUrl ?>" />
            </div>
        <?php endif; ?>
        <?php if ($barcodeTemplate == 4): ?>
            <div style="width: <?php echo $imageWidth+10?>px; magin:2px; float: left; text-align: left;">
                <img name="barcode_images" src="<?php echo $imageUrl ?>" />
                <ul style="font-size: <?php echo $fontSize ?>px; list-style: outside none none; margin: 0; font-size: 12px; padding:0">
                    <li><?php echo $product->getName() ?></li>
                    <li><?php echo $this->__('Size: ') ?><?php if ($product->getResource()->getAttribute('shirt_size')->getFrontend()->getValue($product) && $product->getResource()->getAttribute('shirt_size')->getFrontend()->getValue($product) != 'No') {
            echo $product->getResource()->getAttribute('shirt_size')->getFrontend()->getValue($product);
        } ?><?php if ($product->getResource()->getAttribute('shoe_size')->getFrontend()->getValue($product) && $product->getResource()->getAttribute('shoe_size')->getFrontend()->getValue($product) != 'No') {
            echo $product->getResource()->getAttribute('shoe_size')->getFrontend()->getValue($product);
        } ?><?php if ($product->getResource()->getAttribute('ram_size')->getFrontend()->getValue($product) && $product->getResource()->getAttribute('ram_size')->getFrontend()->getValue($product) != 'No') {
            echo $product->getResource()->getAttribute('ram_size')->getFrontend()->getValue($product);
        } ?></li>
                    <li><?php echo $this->__('Color: ') ?><?php echo $product->getResource()->getAttribute('color')->getFrontend()->getValue($product) ?><span style="margin-left:10px; font-size:<?php echo $fontSize ?>px;"><?php echo Mage::helper('core')->currency($product->getPrice()) ?></span></div></li>
                </ul>
            </div>
        <?php endif; ?>
<?php endfor; ?>

</div>
