<?php
$reviewData = Mage::helper('mobistorelocator2/review')->getReviewData(); 
$overAllRating = Mage::helper('mobistorelocator2/review')->getAllOverRatings($reviewData); 
$deleteUrl = Mage::helper('mobistorelocator2/review')->getDeleteUrl();  
$backUrl = Mage::helper('mobistorelocator2/review')->getBackUrl(); 
?>
<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?=$this->__('Edit Store Review')?></h3></td>
            <td class="a-right">
                <button onclick="<?php echo "setLocation('".$backUrl."')"?>" class="scalable back" type="button"><span><?php echo $this->__('Back')?></span></button>
				<button onclick="<?php echo "deleteConfirm('Are you sure you want to do this?', '".$deleteUrl."')"?>" class="scalable delete" type="button"><span><?php echo $this->__('Delete Review')?></span></button>
				<button onclick="review_form.submit(); aftersuccess();" class="scalable save" type="button"><span><?php echo $this->__('Save Review')?></span></button>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <form action="<?php echo $this->getUrl('*/*/update');?>" method="POST" name="review_form">
	    <input type="hidden" value="<?php echo Mage::app()->getRequest()->getParam('reviewid')?>" name="storereview_id">
		<input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>" />
		<div class="entry-edit-head">
			<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Review Details')?></h4>
			<div class="form-buttons"></div>
		</div>
		<div id="review_details" class="fieldset fieldset-wide">
		    <div id="review_details" class="fieldset fieldset-wide">
				<div class="">
				    <table class="form-list" cellspacing="0">
					    <tbody>
						     <tr>
							     <td class="label">
								     <label for="store_name"><?php echo $this->__('Store')?></label>
							     </td>
								 <td class="value">
								     <span id="store_name"><?php echo Mage::helper('mobistorelocator2/review')->getStoreName()?></span>
							     </td>
						     </tr>
							 <tr>
							     <td class="label">
								     <label for="customer"><?php echo $this->__('Posted By')?></label>
							     </td>
								 <td class="value" style="text-align:left;">
								     <span id="customer" ><?php echo $reviewData['nick_name']?></span>
									 <span>
									 <?php if($reviewData['customer_id']):?>
									     <a href="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/customer/edit" , array('id' => $reviewData['customer_id']))?>"><?php echo $this->__('Customer')?></a>
									 <?php else:?>
									    <?php echo $this->__('Guest User')?>
									 <?php endif;?>
									 </span>
							     </td>
						     </tr>
							 <tr>
							     <td class="label">
								     <label for="customeremail"><?php echo $this->__('Email')?></label>
							     </td>
								 <td class="value" style="text-align:left;">
								     <span id="customeremail" ><?php echo $reviewData['email_id']?></span>
							     </td>
						     </tr>							 
							 <tr>
							     <td class="label">
								     <label for="customer"><?php echo $this->__('Detailed Rating')?></label>
							     </td>
								 <td class="value">
								     <span id="summary_rating ">  <div class="product-review-box">  
									     <table cellspacing="0" id="product-review-table">
											<thead>
												<tr>
													<th><span class="nobr"><?php echo Mage::helper('rating')->__('Rating By') ?></span></th>
													<th><span class="nobr"><?php echo Mage::helper('rating')->__('1 star') ?></span></th>
													<th><span class="nobr"><?php echo Mage::helper('rating')->__('2 stars') ?></span></th>
													<th><span class="nobr"><?php echo Mage::helper('rating')->__('3 stars') ?></span></th>
													<th><span class="nobr"><?php echo Mage::helper('rating')->__('4 stars') ?></span></th>
													<th><span class="nobr"><?php echo Mage::helper('rating')->__('5 stars') ?></span></th>
												</tr>
											</thead>
											<tbody>
												<?php 
												$rating_col = Mage::getModel('mobistorelocator2/rating')->getCollection();
												$review_values =  unserialize($reviewData['value']);
												?>
												<?php if($rating_col->getSize()):?>
													<?php foreach($rating_col as $rating):?>
														<tr>
															<?php
															$mr_name = $rating->getMrName();
															$all_labels = unserialize($mr_name);
															$defaultlabel = $all_labels['default'];

															?>
															<td><?php echo $defaultlabel
															?></td>
															<?php for($i=1; $i<=5; $i++): ?>
															   <td><input <?php if($review_values['ratings'][$rating->getMrId()]['value'] == $i) echo 'checked'?> type="radio" value="<?php echo $i?>"  name="ratings[<?php echo $rating->getMrId()?>][value]"></td>
															<?php endfor;?>
													    </tr>
													<?php endforeach;?>
												<?php endif;?>
												
											</tbody>
										</table></div>
									 </span>
							     </td>
						     </tr>
							 <tr>
							     <td class="label">
								     <label for="status_id"><?php echo $this->__('Status ')?></label>
							     </td>
								 <td class="value">
								     <select class=" required-entry select" name="status_id" id="status_id">
										<option <?php if($reviewData['status_id'] == 1) echo "selected=\"selected\""?> value="1"><?php echo $this->__('Approved')?></option>
										<option <?php if($reviewData['status_id'] == 2) echo "selected=\"selected\""?> value="2"><?php echo $this->__('Pending')?></option>
										<option <?php if($reviewData['status_id'] == 3) echo "selected=\"selected\""?> value="3"><?php echo $this->__('Not Approved')?></option>
									</select>
							     </td>
						     </tr>
							 <tr>
							     <td class="label">
								     <label for="summary"><?php echo $this->__('Summary ')?></label>
							     </td>
								 <td class="value">
								      <input type="text" class=" input-text required-entry" value="<?php echo $reviewData['summary']?>" name="summary" id="summary">								      
							     </td>
						     </tr>
							 <tr>
							     <td class="label">
								     <label for="comment"><?php echo $this->__('Review ')?></label>
							     </td>
								 <td class="value">								      
									  <textarea class=" required-entry textarea" cols="15" rows="2" style="height:24em;" name="comment" id="comment"><?php echo $reviewData['comment']?></textarea>
							     </td>
						     </tr>
					    </tbody>
					</table>
				</div>
			</div>
		</div>
	</form>
</div>
<script type="text/javascript">
//<![CDATA[
    Validation.addAllThese(
    [
           ['validate-rating', '<?php echo Mage::helper('rating')->__('Please select one of each ratings above') ?>', function(v) {
                var trs = $('product-review-table').getElementsBySelector('tr');
                var inputs;
                var error = 1;

                for( var j=0; j < trs.length; j++ ) {
                    var tr = trs[j];
                    if( j > 0 ) {
                        inputs = tr.getElementsBySelector('input');

                        for( i in inputs ) {
                            if( inputs[i].checked == true ) {
                                error = 0;
                            }
                        }

                        if( error == 1 ) {
                            //console.log(tr)
                            return false;
                        } else {
                            error = 1;
                        }
                    }
                }
                return true;
            }]
    ]
    );
//]]>
</script>

