<?php
$advancesettings = $this->getAdvanceSettings();
$productAttributes = Mage::helper('mobiadmin2')->getProductAttributes();
$categories = $this->getFirstLevelCategories();
?>

<div class="advancesettings entry-edit">
	<div class="entry-edit-head">
	    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Category Settings <span class="app-scope">[Website]</span>')?></h4>
	</div>
	<div class="fieldset">
		<p class="guideline-text"><?php echo $this->__('Selected categories will be displayed in Category menu of the mobile app.'); ?></p>
		<table cellspacing="0" class="form-list">
			<tbody>
				<tr>
					<td class="label"><?php echo $this->__('Categories To Show : ')?></td>
					<td class="value">
						<?php
						if($categories){
							foreach($categories as $_category){
								?>
								<label for="category_<?php echo $_category['id']; ?>">
									<input type="checkbox" <?php if(isset($advancesettings['categories'][$_category['id']])) echo 'checked'; ?> id="category_<?php echo $_category['id']; ?>" name="advancesettings[categories][<?php echo $_category['id']; ?>]" />&nbsp;<?php echo $_category['name']; ?>
								</label>
								<br />
								<?php
							}
						}
						?>
					</td>
				</tr>
			</tbody>
		</table>
	</div>

	<div class="entry-edit-head">
	    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Image Settings <span class="app-scope">[Website]</span>')?></h4>
	</div>
	<div class="fieldset">
		<p class="guideline-text"><?php echo $this->__('Define shape of the images you are using for the website/mobile app, image container in mobile app will be adjust according to defined shapes and make the app best suit according to your product line.'); ?></p>
		<table cellspacing="0" class="form-list">
			<tbody>
				<tr>
					<td class="label"><?php echo $this->__('Category Images : ')?></td>
					<td class="value">
						<select name="advancesettings[image][category]">
							<option value="square" <?php if(isset($advancesettings['image']['category']) && $advancesettings['image']['category'] == 'square') echo "selected"; ?>><?php echo $this->__('Square'); ?></option>
							<option value="vertical_rectangle" <?php if(isset($advancesettings['image']['category']) && $advancesettings['image']['category'] == 'vertical_rectangle') echo "selected"; ?>><?php echo $this->__('Vertical Rectangle'); ?></option>
							<option value="horizontal_rectangle" <?php if(isset($advancesettings['image']['category']) && $advancesettings['image']['category'] == 'horizontal_rectangle') echo "selected"; ?>><?php echo $this->__('Horizontal Rectangle'); ?></option>
						</select>
					</td>
				</tr>
				<tr>
					<td class="label"><?php echo $this->__('Product Images : ')?></td>
					<td class="value">
						<select name="advancesettings[image][product]">
							<option value="square" <?php if(isset($advancesettings['image']['product']) && $advancesettings['image']['product'] == 'square') echo "selected"?>><?php echo $this->__('Square'); ?></option>
							<option value="vertical_rectangle" <?php if(isset($advancesettings['image']['product']) && $advancesettings['image']['product'] == 'vertical_rectangle') echo "selected"; ?>><?php echo $this->__('Vertical Rectangle'); ?></option>
							<option value="horizontal_rectangle" <?php if(isset($advancesettings['image']['product']) && $advancesettings['image']['product'] == 'horizontal_rectangle') echo "selected"; ?>><?php echo $this->__('Horizontal Rectangle'); ?></option>
						</select>
					</td>
				</tr>
			</tbody>
		</table>
	</div>

    <div class="entry-edit-head">
	    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Miscellaneous Settings <span class="app-scope">[Website]</span>')?></h4>
	</div>
	<div class="fieldset">
		<p class="guideline-text"><?php echo $this->__('Enable/disable module or features for the whole mobile app, disabled module will no longer available in the mobile app.'); ?></p>
		<table cellspacing="0" class="form-list">
			<tbody>
				<tr>
					<td class="label"><?php echo $this->__('Enable Rating Feature : ')?></td>
					<td class="value">
						<input <?php if(isset($advancesettings['miscellaneous']['enable_rating']) && $advancesettings['miscellaneous']['enable_rating'] == 1) echo "checked"; ?> type="radio" value="1" name="advancesettings[miscellaneous][enable_rating]" />&nbsp;<?php echo $this->__('Yes'); ?>
						<input <?php if(isset($advancesettings['miscellaneous']['enable_rating']) && $advancesettings['miscellaneous']['enable_rating'] == 0) echo "checked"; ?> type="radio" value="0" name="advancesettings[miscellaneous][enable_rating]" />&nbsp;<?php echo $this->__('No'); ?>
					</td>
				</tr>
				<tr>
					<td class="label"><?php echo $this->__('Enable Wishlist Feature : ')?></td>
					<td class="value">
						<input <?php if(isset($advancesettings['miscellaneous']['enable_wishlist']) && $advancesettings['miscellaneous']['enable_wishlist'] == 1) echo "checked"; ?> type="radio" value="1" name="advancesettings[miscellaneous][enable_wishlist]" />&nbsp;<?php echo $this->__('Yes'); ?>
						<input <?php if(isset($advancesettings['miscellaneous']['enable_wishlist']) && $advancesettings['miscellaneous']['enable_wishlist'] == 0) echo "checked"; ?> type="radio" value="0" name="advancesettings[miscellaneous][enable_wishlist]" />&nbsp;<?php echo $this->__('No'); ?>
					</td>
				</tr>
				<tr>
					<td class="label"><?php echo $this->__('Enable Social Media Sharing : ')?></td>
					<td class="value">
						<input <?php if(isset($advancesettings['miscellaneous']['enable_socialsharing']) && $advancesettings['miscellaneous']['enable_socialsharing'] == 1) echo "checked"; ?> type="radio" value="1" name="advancesettings[miscellaneous][enable_socialsharing]" />&nbsp;<?php echo $this->__('Yes'); ?>
						<input <?php if(isset($advancesettings['miscellaneous']['enable_socialsharing']) && $advancesettings['miscellaneous']['enable_socialsharing'] == 0) echo "checked"; ?> type="radio" value="0" name="advancesettings[miscellaneous][enable_socialsharing]" />&nbsp;<?php echo $this->__('No'); ?>
					</td>
				</tr>
				<tr>
					<td class="label"><?php echo $this->__('Enable Discount Coupon : ')?></td>
					<td class="value">
						<input <?php if(isset($advancesettings['miscellaneous']['enable_discountcoupon']) && $advancesettings['miscellaneous']['enable_discountcoupon'] == 1) echo "checked"; ?> type="radio" value="1" name="advancesettings[miscellaneous][enable_discountcoupon]" />&nbsp;<?php echo $this->__('Yes'); ?>
						<input <?php if(isset($advancesettings['miscellaneous']['enable_discountcoupon']) && $advancesettings['miscellaneous']['enable_discountcoupon'] == 0) echo "checked"; ?> type="radio" value="0" name="advancesettings[miscellaneous][enable_discountcoupon]" />&nbsp;<?php echo $this->__('No'); ?>
					</td>
				</tr>
				<tr>
					<td class="label"><?php echo $this->__('Enable Product Search Facility : ')?></td>
					<td class="value">
						<input <?php if(isset($advancesettings['miscellaneous']['enable_productsearch']) && $advancesettings['miscellaneous']['enable_productsearch'] == 1) echo "checked"; ?> type="radio" value="1" name="advancesettings[miscellaneous][enable_productsearch]" />&nbsp;<?php echo $this->__('Yes'); ?>
						<input <?php if(isset($advancesettings['miscellaneous']['enable_productsearch']) && $advancesettings['miscellaneous']['enable_productsearch'] == 0) echo "checked"; ?> type="radio" value="0" name="advancesettings[miscellaneous][enable_productsearch]" />&nbsp;<?php echo $this->__('No'); ?>
					</td>
				</tr>
				<tr>
					<td class="label"><?php echo $this->__('Enable Guest Checkout : ')?></td>
					<td class="value">
						<input <?php if(isset($advancesettings['miscellaneous']['enable_guestcheckout']) && $advancesettings['miscellaneous']['enable_guestcheckout'] == 1) echo "checked"; ?> type="radio" value="1" name="advancesettings[miscellaneous][enable_guestcheckout]" />&nbsp;<?php echo $this->__('Yes'); ?>
						<input <?php if(isset($advancesettings['miscellaneous']['enable_guestcheckout']) && $advancesettings['miscellaneous']['enable_guestcheckout'] == 0) echo "checked"; ?> type="radio" value="0" name="advancesettings[miscellaneous][enable_guestcheckout]" />&nbsp;<?php echo $this->__('No'); ?>
					</td>
				</tr>
				<tr>
					<td class="label"><?php echo $this->__('Hide Out of Stock Items : ')?></td>
					<td class="value">
						<input <?php if(isset($advancesettings['miscellaneous']['enable_outofstock']) && $advancesettings['miscellaneous']['enable_outofstock'] == 1) echo "checked"; ?> type="radio" value="1" name="advancesettings[miscellaneous][enable_outofstock]" />&nbsp;<?php echo $this->__('Yes'); ?>
						<input <?php if(isset($advancesettings['miscellaneous']['enable_outofstock']) && $advancesettings['miscellaneous']['enable_outofstock'] == 0) echo "checked"; ?> type="radio" value="0" name="advancesettings[miscellaneous][enable_outofstock]" />&nbsp;<?php echo $this->__('No'); ?>
					</td>
				</tr>
				<tr>
					<td class="label"><?php echo $this->__('Enable Fixed Header : ')?></td>
					<td class="value">
						<input <?php if(isset($advancesettings['miscellaneous']['enable_fixedheader']) && $advancesettings['miscellaneous']['enable_fixedheader'] == 1) echo "checked"; ?> type="radio" value="1" name="advancesettings[miscellaneous][enable_fixedheader]" />&nbsp;<?php echo $this->__('Yes'); ?>
						<input <?php if(isset($advancesettings['miscellaneous']['enable_fixedheader']) && $advancesettings['miscellaneous']['enable_fixedheader'] == 0) echo "checked"; ?> type="radio" value="0" name="advancesettings[miscellaneous][enable_fixedheader]" />&nbsp;<?php echo $this->__('No'); ?>
					</td>
				</tr>
				<tr>
					<td class="label"><?php echo $this->__('Enable Estimated Shipping Cost : ')?></td>
					<td class="value">
						<input <?php if(isset($advancesettings['miscellaneous']['enable_estimatedshippingcost']) && $advancesettings['miscellaneous']['enable_estimatedshippingcost'] == 1) echo "checked"; ?> type="radio" value="1" name="advancesettings[miscellaneous][enable_estimatedshippingcost]" />&nbsp;<?php echo $this->__('Yes'); ?>
						<input <?php if(isset($advancesettings['miscellaneous']['enable_estimatedshippingcost']) && $advancesettings['miscellaneous']['enable_estimatedshippingcost'] == 0) echo "checked"; ?> type="radio" value="0" name="advancesettings[miscellaneous][enable_estimatedshippingcost]" />&nbsp;<?php echo $this->__('No'); ?>
					</td>
				</tr>
				<tr>
					<td class="label"><?php echo $this->__('Enable Category Widgets : ')?></td>
					<td class="value">
						<input <?php if(isset($advancesettings['miscellaneous']['enable_categorywidget']) && $advancesettings['miscellaneous']['enable_categorywidget'] == 1) echo "checked"; ?> type="radio" value="1" name="advancesettings[miscellaneous][enable_categorywidget]" />&nbsp;<?php echo $this->__('Yes'); ?>
						<input <?php if(isset($advancesettings['miscellaneous']['enable_categorywidget']) && $advancesettings['miscellaneous']['enable_categorywidget'] == 0) echo "checked"; ?> type="radio" value="0" name="advancesettings[miscellaneous][enable_categorywidget]" />&nbsp;<?php echo $this->__('No'); ?>
					</td>
				</tr>
				<tr>
					<td class="label"><?php echo $this->__('Enable Storelocator : ')?></td>
					<td class="value">
						<input <?php if(isset($advancesettings['miscellaneous']['enable_storelocator']) && $advancesettings['miscellaneous']['enable_storelocator'] == 1) echo "checked"; ?> type="radio" value="1" name="advancesettings[miscellaneous][enable_storelocator]" />&nbsp;<?php echo $this->__('Yes'); ?>
						<input <?php if(isset($advancesettings['miscellaneous']['enable_storelocator']) && $advancesettings['miscellaneous']['enable_storelocator'] == 0) echo "checked"; ?> type="radio" value="0" name="advancesettings[miscellaneous][enable_storelocator]" />&nbsp;<?php echo $this->__('No'); ?>
					</td>
				</tr>
				<tr>
					<td class="label"><?php echo $this->__('Enable Social Login : ')?></td>
					<td class="value">
						<input <?php if(isset($advancesettings['miscellaneous']['enable_sociallogin']) && $advancesettings['miscellaneous']['enable_sociallogin'] == 1) echo "checked"; ?> type="radio" value="1" name="advancesettings[miscellaneous][enable_sociallogin]" />&nbsp;<?php echo $this->__('Yes'); ?>
						<input <?php if(isset($advancesettings['miscellaneous']['enable_sociallogin']) && $advancesettings['miscellaneous']['enable_sociallogin'] == 0) echo "checked"; ?> type="radio" value="0" name="advancesettings[miscellaneous][enable_sociallogin]" />&nbsp;<?php echo $this->__('No'); ?>
					</td>
				</tr>
				<tr>
					<td class="label"><?php echo $this->__('Enable Image Resize : ')?></td>
					<td class="value">
						<input <?php if(isset($advancesettings['miscellaneous']['enable_image_resize']) && $advancesettings['miscellaneous']['enable_image_resize'] == 1) echo "checked"; ?> type="radio" value="1" name="advancesettings[miscellaneous][enable_image_resize]" />&nbsp;<?php echo $this->__('Yes'); ?>
						<input <?php if(isset($advancesettings['miscellaneous']['enable_image_resize']) && $advancesettings['miscellaneous']['enable_image_resize'] == 0) echo "checked"; ?> type="radio" value="0" name="advancesettings[miscellaneous][enable_image_resize]" />&nbsp;<?php echo $this->__('No'); ?>
					</td>
				</tr>
				<tr>
					<td class="label"></td>
					<td class="value">
						<?php echo $this->__('Enable Image Resize: This feature will let you enable/disable image resize on your app. By default, our app will resize images to display properly on various sizes of mobiles and tablets screens. Sometimes, due to insufficient permission from server it won\'t allow our extension to resize image and will throw an error or it will not display images. In such case, you can disable Image Resize to display images on app. It will help you in making your mobile app look clear with images with same dimensions.'); ?>
					</td>
				</tr>
			</tbody>
		</table>
	</div>

	<div class="entry-edit-head">
	    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Product Listing Settings <span class="app-scope">[Website]</span>')?></h4>
	</div>
	<div class="fieldset">
		<table cellspacing="0" class="form-list">
			<tbody>
				<tr>
					<td class="label"><?php echo $this->__('Show Product Name : ')?></td>
					<td class="value">
						<input <?php if(isset($advancesettings['productlist']['showname']) && $advancesettings['productlist']['showname'] == 1) echo "checked"; ?> type="radio" value="1" name="advancesettings[productlist][showname]" />&nbsp;<?php echo $this->__('Yes'); ?>
						<input <?php if(isset($advancesettings['productlist']['showname']) && $advancesettings['productlist']['showname'] == 0) echo "checked"; ?> type="radio" value="0" name="advancesettings[productlist][showname]" />&nbsp;<?php echo $this->__('No'); ?>
					</td>
				</tr>
				<tr>
					<td class="label"><?php echo $this->__('Show Product Price : ')?></td>
					<td class="value">
						<input <?php if(isset($advancesettings['productlist']['showprice']) && $advancesettings['productlist']['showprice'] == 1) echo "checked"; ?> type="radio" value="1" name="advancesettings[productlist][showprice]" />&nbsp;<?php echo $this->__('Yes'); ?>
						<input <?php if(isset($advancesettings['productlist']['showprice']) && $advancesettings['productlist']['showprice'] == 0) echo "checked"; ?> type="radio" value="0" name="advancesettings[productlist][showprice]" />&nbsp;<?php echo $this->__('No'); ?>
					</td>
				</tr>
				<tr>
					<td class="label"><?php echo $this->__('Show Product Rating : ')?></td>
					<td class="value">
						<input <?php if(isset($advancesettings['productlist']['showrating']) && $advancesettings['productlist']['showrating'] == 1) echo "checked"; ?> type="radio" value="1" name="advancesettings[productlist][showrating]" />&nbsp;<?php echo $this->__('Yes'); ?>
						<input <?php if(isset($advancesettings['productlist']['showrating']) && $advancesettings['productlist']['showrating'] == 0) echo "checked"; ?> type="radio" value="0" name="advancesettings[productlist][showrating]" />&nbsp;<?php echo $this->__('No'); ?>
					</td>
				</tr>
				<tr>
					<td class="label"><?php echo $this->__('Enable Sort By option : ')?></td>
					<td class="value">
						<input <?php if(isset($advancesettings['productlist']['enablesort']) && $advancesettings['productlist']['enablesort'] == 1) echo "checked"; ?> type="radio" value="1" name="advancesettings[productlist][enablesort]" />&nbsp;<?php echo $this->__('Yes'); ?>
						<input <?php if(isset($advancesettings['productlist']['enablesort']) && $advancesettings['productlist']['enablesort'] == 0) echo "checked"; ?> type="radio" value="0" name="advancesettings[productlist][enablesort]" />&nbsp;<?php echo $this->__('No'); ?>
					</td>
				</tr>
				<tr>
					<td class="label"><?php echo $this->__('Default Product Sorting : ')?></td>
					<td class="value">
						<select name="advancesettings[productlist][default_sorting]">
							<option value="popularity" <?php if(isset($advancesettings['productlist']['default_sorting']) && $advancesettings['productlist']['default_sorting'] == 'popularity') echo "selected"?>>Popularity</option>
							<option value="position" <?php if(isset($advancesettings['productlist']['default_sorting']) && $advancesettings['productlist']['default_sorting'] == 'position') echo "selected"?>>Position</option>
							<option value="price-h-l" <?php if(isset($advancesettings['productlist']['default_sorting']) && $advancesettings['productlist']['default_sorting'] == 'price-h-l') echo "selected"?>>Price High to Low</option>
							<option value="price-l-h" <?php if(isset($advancesettings['productlist']['default_sorting']) && $advancesettings['productlist']['default_sorting'] == 'price-l-h') echo "selected"?>>Price Low to High</option>
							<option value="rating-h-l" <?php if(isset($advancesettings['productlist']['default_sorting']) && $advancesettings['productlist']['default_sorting'] == 'rating-h-l') echo "selected"?>>Rating</option>
							<option value="name-a-z" <?php if(isset($advancesettings['productlist']['default_sorting']) && $advancesettings['productlist']['default_sorting'] == 'name-a-z') echo "selected"?>>Name A-Z</option>
							<option value="name-z-a" <?php if(isset($advancesettings['productlist']['default_sorting']) && $advancesettings['productlist']['default_sorting'] == 'name-z-a') echo "selected"?>>Name Z-A</option>
							<option value="newest" <?php if(isset($advancesettings['productlist']['default_sorting']) && $advancesettings['productlist']['default_sorting'] == 'newest') echo "selected"?>>Newest</option>
						</select>
					</td>
				</tr>
				<tr>
					<td class="label"><?php echo $this->__('Default Product View : ')?></td>
					<td class="value">
						<select name="advancesettings[productlist][default_view]">
							<option value="grid" <?php if(isset($advancesettings['productlist']['default_view']) && $advancesettings['productlist']['default_view'] == 'grid') echo "selected"?>>Grid</option>
							<option value="list" <?php if(isset($advancesettings['productlist']['default_view']) && $advancesettings['productlist']['default_view'] == 'list') echo "selected"?>>List</option>
							<option value="image" <?php if(isset($advancesettings['productlist']['default_view']) && $advancesettings['productlist']['default_view'] == 'image') echo "selected"?>>Image</option>
						</select>
					</td>
				</tr>
				<tr>
					<td class="label"><?php echo $this->__('Enable Change Product View Option : ')?></td>
					<td class="value">
						<input <?php if(isset($advancesettings['productlist']['enablechangeproductview']) && $advancesettings['productlist']['enablechangeproductview'] == 1) echo "checked"; ?> type="radio" value="1" name="advancesettings[productlist][enablechangeproductview]" />&nbsp;<?php echo $this->__('Yes'); ?>
						<input <?php if(isset($advancesettings['productlist']['enablechangeproductview']) && $advancesettings['productlist']['enablechangeproductview'] == 0) echo "checked"; ?> type="radio" value="0" name="advancesettings[productlist][enablechangeproductview]" />&nbsp;<?php echo $this->__('No'); ?>
					</td>
				</tr>
				<tr>
					<td class="label"><?php echo $this->__('Persistent View : ')?></td>
					<td class="value">
						<input <?php if(isset($advancesettings['productlist']['persistent_view']) && $advancesettings['productlist']['persistent_view'] == 1) echo "checked"; ?> type="radio" value="1" name="advancesettings[productlist][persistent_view]" />&nbsp;<?php echo $this->__('Yes'); ?>
						<input <?php if(isset($advancesettings['productlist']['persistent_view']) && $advancesettings['productlist']['persistent_view'] == 0) echo "checked"; ?> type="radio" value="0" name="advancesettings[productlist][persistent_view]" />&nbsp;<?php echo $this->__('No'); ?>
					</td>
				</tr>
				<tr>
					<td class="label"><?php echo $this->__('Enable Filter Option : ')?></td>
					<td class="value">
						<input <?php if(isset($advancesettings['productlist']['enablefilter']) && $advancesettings['productlist']['enablefilter'] == 1) echo "checked"; ?> type="radio" value="1" name="advancesettings[productlist][enablefilter]" />&nbsp;<?php echo $this->__('Yes'); ?>
						<input <?php if(isset($advancesettings['productlist']['enablefilter']) && $advancesettings['productlist']['enablefilter'] == 0) echo "checked"; ?> type="radio" value="0" name="advancesettings[productlist][enablefilter]" />&nbsp;<?php echo $this->__('No'); ?>
					</td>
				</tr>
			</tbody>
		</table>
	</div>

	<div class="entry-edit-head">
	    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Product Detail Settings <span class="app-scope">[Website]</span>')?></h4>
	</div>
	<div class="fieldset">
		<table cellspacing="0" class="form-list">
			<tbody>
				<tr>
					<td class="label"><?php echo $this->__('Enable product Zoom : ')?></td>
					<td class="value">
						<input <?php if(isset($advancesettings['productdetail']['enable_productzoom']) && $advancesettings['productdetail']['enable_productzoom'] == 1) echo "checked"; ?> type="radio" value="1" name="advancesettings[productdetail][enable_productzoom]" />&nbsp;<?php echo $this->__('Yes'); ?>
						<input <?php if(isset($advancesettings['productdetail']['enable_productzoom']) && $advancesettings['productdetail']['enable_productzoom'] == 0) echo "checked"; ?> type="radio" value="0" name="advancesettings[productdetail][enable_productzoom]" />&nbsp;<?php echo $this->__('No'); ?>
					</td>
				</tr>
				<tr>
					<td class="label"><?php echo $this->__('Enable Endless Slider : ')?></td>
					<td class="value">
						<input <?php if(isset($advancesettings['productdetail']['enable_endless_slider']) && $advancesettings['productdetail']['enable_endless_slider'] == 1) echo "checked"; ?> type="radio" value="1" name="advancesettings[productdetail][enable_endless_slider]" />&nbsp;<?php echo $this->__('Yes'); ?>
						<input <?php if(isset($advancesettings['productdetail']['enable_endless_slider']) && $advancesettings['productdetail']['enable_endless_slider'] == 0) echo "checked"; ?> type="radio" value="0" name="advancesettings[productdetail][enable_endless_slider]" />&nbsp;<?php echo $this->__('No'); ?>
					</td>
				</tr>
				<tr>
					<td class="label"><?php echo $this->__('Enable "You may like" products slider : ')?></td>
					<td class="value">
						<input <?php if(isset($advancesettings['productdetail']['enable_youmaylike_slider']) && $advancesettings['productdetail']['enable_youmaylike_slider'] == 1) echo "checked"; ?> type="radio" value="1" name="advancesettings[productdetail][enable_youmaylike_slider]" />&nbsp;<?php echo $this->__('Yes'); ?>
						<input <?php if(isset($advancesettings['productdetail']['enable_youmaylike_slider']) && $advancesettings['productdetail']['enable_youmaylike_slider'] == 0) echo "checked"; ?> type="radio" value="0" name="advancesettings[productdetail][enable_youmaylike_slider]" />&nbsp;<?php echo $this->__('No'); ?>
					</td>
				</tr>
				<tr>
					<td class="label"><?php echo $this->__('Show Product Information : ')?></td>
					<td class="value">
						<?php
						if($productAttributes){
							foreach($productAttributes as $_attr){
								?>
								<label for="showattribute_<?php echo $_attr['code']; ?>">
									<input type="checkbox" <?php if(!isset($advancesettings['productdetail']['showattribute'])) echo 'checked'; else if(!array_key_exists($_attr['code'], $advancesettings['productdetail']['showattribute'])) echo "checked"; ?> id="showattribute_<?php echo $_attr['code']; ?>" name="advancesettings[productdetail][showattribute][<?php echo $_attr['code']; ?>]" />&nbsp;<?php echo $_attr['label']; ?>
								</label>
								<br />
								<?php
							}
						}
						?>
					</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>