<div class="support-column">
	<img src="<?php echo $this->getSkinUrl('images/mobiadmin2/needhelp.gif')?>" />
    <ul>
    	<li><a target="_blank" href="http://mobicommerce.net/" class="live-support"><img src="<?php echo $this->getSkinUrl('images/mobiadmin2/sup-1.png')?>" /><?php echo $this->__('Live Support')?></a></li>
        <li><img src="<?php echo $this->getSkinUrl('images/mobiadmin2/sup-2.png')?>" class="contact-icon"/>+1-347-979-7106 (GMT +5.5)</li>
        <li><img src="<?php echo $this->getSkinUrl('images/mobiadmin2/sup-2.png')?>" class="contact-icon"/>+91-79-40037111</li>
        <li><a target="_top" href="mailto:support@mobicommerce.net"><img src="<?php echo $this->getSkinUrl('images/mobiadmin2/sup-3.png')?>" class="email-icon"/>support@mobicommerce.net</a></li>
        <li><a target="_blank" href="http://support.mobicommerce.net/"><img src="<?php echo $this->getSkinUrl('images/mobiadmin2/sup-4.png')?>" class="email-icon"/>support.mobicommerce.net/</a></li>
    </ul>
</div>