<?php 
$Homewidget = Mage::getModel('mobiadmin2/widget')->getCollection();
$Homewidget->setOrder('widget_position','ASC');

$id = Mage::app()->getRequest()->getParam('id');
$model = Mage::getModel('mobiadmin2/applications');
$model->load((int) $id);
$versionType = $model->getVersionType();
if(!in_array($versionType, array('001', '002')))
	$versionType = '001';
?>
<input type="hidden" name="widgetChange" id="widgetChange" value="0">
<div class="home-widget-content">
	<div class="content-header">
		<table cellspacing="0" class="grid-header">
			<tr>	
				<td class="a-right">
					<button onclick="showwidgets()" class="scalable save" type="button"><span><?php echo $this->__('Widgets List')?></span></button>
					<?php if($versionType == '002'): ?>
						<button onclick="createwidget()" class="scalable save" type="button"><span><?php echo $this->__('Add New Widget')?></span></button>
					<?php endif; ?>
				</td>
			</tr>
		</table>
	</div>
</div>
<div class="widget-lists">
	<?php echo $this->getLayout()->createBlock('adminhtml/template')->setTemplate('mobiadmin2/application/edit/tab/widget/widgetlist.phtml')->toHtml();?>
</div>
<div class="content-widget-new1"></div>

<script>
	function createwidget(){
		markWidgetChange();
		new Ajax.Request("<?php echo Mage::helper('adminhtml')->getUrl('mobicommerce2/widget/createwidget')?>", {
			method: 'Post',
			parameters: {isAjax : 1},
			onComplete: function(data) {				    
			},
			onSuccess: function(response){
				var json = response.responseText.evalJSON(true);
				if(json.status == 'success'){
		            jQuery('.content-widget-new').html(json.widget_new_block);
				}
				else{
					alert(json.error);
				}
			},
			onFailure: function(response){
				var json = response.responseText.evalJSON(true);
				alert(json.error);
			}
		});
	}
	function showwidgets(){
		markWidgetChange();
		var param = "<?php echo Mage::app()->getRequest()->getParam('store');?>";
		var appid = "<?php echo Mage::app()->getRequest()->getParam('id');?>";
		var url ="<?php echo Mage::helper('adminhtml')->getUrl('mobicommerce2/widget/widgetlist')?>store/"+param+'/id/'+appid;
		new Ajax.Request(url, {
			method: 'Post',
			parameters: {isAjax : 1},
			onComplete: function(data) {				    
			},
			onSuccess: function(response){
				var json = response.responseText.evalJSON(true);
				if(json.status == 'success'){
		            jQuery('.widget-lists').html(json.widget_list_block);
				}
				else{
					alert(json.error);
				}
			},
			onFailure: function(response){
				var json = response.responseText.evalJSON(true);
				alert(json.error);
			}
		});
	}
	function markWidgetChange()
	{
		jQuery('#widgetChange').val('1');
	}
</script>