<div class="entry-edit">
    <div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('CMS Pages')?></h4>
	</div>
	<div class="fieldset ">
		<div class="hor-scroll">
			<table class="form-list" cellspacing="0">
			    <tbody>
					<input id="linktype" type="hidden" name="type" value="cms">
					<tr>
						<td colspan="2"><div class="product-grid"><?php echo $this->getLayout()->createBlock('mobiadmin2/adminhtml_applications_grid_widget_deeplink_cms')->toHtml();?></div></td>
					</tr>
			    </tbody>
			</table>
		</div>
	</div>		
</div>