<?php
$external_link_url = Mage::app()->getRequest()->getParam('link_type_value');
?>
<div class="entry-edit">
    <div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('External Web Page URL'); ?></h4>
	</div>
	<div class="fieldset ">
		<div class="hor-scroll">
			<table class="form-list" cellspacing="0">
			    <tbody>
				    <tr>
						<input id="linktype" type="hidden" name="type" value="external">
					    <td class="label"><label for="website_id"><?php echo $this->__('External Web Page URL'); ?></label></td>
						<td class="value">
							<input type="text" class="linktypevalue required-entry input-text required-entry" value="<?php echo $external_link_url; ?>" name="value">
							<br>
							<small class="mbsmall"><?php echo $this->__('Enter web page url starting with http:// or https://'); ?></small>
						</td>
				    </tr>
			    </tbody>
			</table>
		</div>
	</div>	
</div>