<?php
$bannersImages = Mage::helper('mobiadmin')->getBannerImages();
?>
<div class="entry-edit">
    <div class="entry-edit-head">
	    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Home Page Banner Images <span class="app-scope">[STORE VIEW]</span>')?></h4>
	</div>
	<div id="store_information" class="fieldset ">
	    <div class="hor-scroll">
            <table cellspacing="0" class="form-list">
                <tbody>	
                	<?php
                	if(!empty($bannersImages)){
                		foreach($bannersImages as $bannerImageKey => $bannerImage){
                			$bannerName = 'Banner '.($bannerImageKey + 1);
                			$bannerActiveValue = $bannerImage['is_active'];
                			?>
                			<tr>
								<td class="label">
									<label for="<?php echo $bannerImageKey; ?>"><?php echo $this->__($bannerName); ?></label>
								</td>
								<td class="value">
									<img src="<?php echo $bannerImage['url']; ?>" height="100" width="100" />
								</td>
								<td class="value">
									<input type="file" class="input-file" value="<?php echo $bannerImage['url']; ?>" name="banner[<?php echo $bannerImageKey; ?>]" id="banner-<?php echo $bannerImageKey; ?>">            
								</td>
								<td class="label">
									<?php echo $this->__('Active:')?><input type="checkbox" class="checkbox" value="1" name="bannerisactive[<?php echo $bannerImageKey; ?>]" <?php if($bannerActiveValue =='1'){echo 'checked';}?>/>           
								</td>
							 </tr>
                			<?php
                		}
                	}
                	?>			    
					 <?php /* for($bannerIndex =0; $bannerIndex <= 4; $bannerIndex++):?>
						 <?php $bannerName = 'Banner '.($bannerIndex+1);
						 $bannerNameIndex = 'banner'.$bannerIndex;
						 $bannerImageValue = $bannersImages[$bannerIndex]['url'];
						 $bannerActiveValue = $bannersImages[$bannerIndex]['is_active'];
						 ?>
						 <tr>
							<td class="label">
								<label for="<?php echo $bannerName; ?>"><?php echo $this->__($bannerName); ?></label>
							</td>
							<td class="value">
								<img src="<?php echo $bannerImageValue;?>" height="100" width="100" />
							</td>
							<td class="value">
								<input type="file" class="input-file" value="<?php echo $bannerImageValue;?>" name="banner<?php echo $bannerIndex?>" id="banner-<?php echo $bannerIndex?>">            
							</td>
							<td class="label">
								<?php echo $this->__('Active:')?><input type="checkbox" class="checkbox" value="1" name="bannerisactive[banner<?php echo $bannerIndex?>]" <?php if($bannerActiveValue =='1'){echo 'checked';}?>/>           
							</td>
						 </tr>
					 <?php endfor; */?>									   
				</tbody>
			</table>
        </div>    
	 </div>
</div>
<script>
if (jQuery('#upload_iospem_file_delete').length) {
    jQuery('#upload_iospem_file_delete').parent('.delete-image').hide();
}
if (jQuery('#upload_iospem_file_image').length) {
    jQuery('#upload_iospem_file_image').parent('a').hide();
}

</script>