<?php 
$configSettings = Mage::getSingleton('cms/wysiwyg_config')->getConfig();
$configSettings['files_browser_window_url'] = $this->getBaseUrl().'admin/cms_wysiwyg_images/index/';
Mage::getSingleton('cms/wysiwyg_config')->setConfig($configSettings);
$cmsSettings = Mage::helper('mobiadmin')->getAppCmsPage();
$cmsPages = $cmsSettings['cms_pages'];?>
<div class="entry-edit">
    <div class="entry-edit-head">
	    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Store Information [STORE VIEW]')?></h4>
	</div>
	<div id="store_information" class="fieldset ">
	    <div class="hor-scroll">
            <table cellspacing="0" class="form-list">
                <tbody>
				    <tr><div><?php echo $this->__('Manage content pages of the mobile application. These contents will be displayed under Info section of the mobile app.')?></div></tr>
                    <tr>
                        <td class="label"><label for="company_name"><?php echo $this->__('Company Name')?></label></td>
                        <td class="value"><input id="company_name" class=" input-text" type="text" value="<?php echo $cmsSettings['contact_information']['company_name'] ?>" name="contact_information[company_name]"/></td>
					</tr>
					<tr>
                        <td class="label"><label for="address"><?php echo $this->__('Address')?></label></td>
                        <td class="value"><textarea id="company_address" class=" textarea"  value="" name="contact_information[company_address]"><?php echo $cmsSettings['contact_information']['company_address'] ?></textarea></td>
					</tr>
					<tr>
                        <td class="label"><label for="phone_number"><?php echo $this->__('Phone Number')?></label></td>
                        <td class="value"><input id="phone_number" class="input-text" type="text" value="<?php echo $cmsSettings['contact_information']['phone_number'] ?>" name="contact_information[phone_number]"/></td>
					</tr>
					<tr>
                        <td class="label"><label for="email_address"><?php echo $this->__('Email Address')?></label></td>
                        <td class="value"><input id="email_address" class="validate-email input-text" type="email" value="<?php echo $cmsSettings['contact_information']['email_address'] ?>" name="contact_information[email_address]"/></td>
					</tr>
                </tbody>
             </table>
         </div>
	</div>

	<div class="entry-edit-head">
	    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Social Media URLs <span class="app-scope">[STORE VIEW]</span>')?></h4>
	</div>
	

	<div id="store_information" class="fieldset social-url">
	    <div class="hor-scroll">
            <table cellspacing="0" class="form-list">
                <tbody>
				    <tr><div><?php echo $this->__('If you have your social media accounts/pages, than activate respective social media plate form and Supply their URL. Activated plate form icons will be displayed on Info section page.')?></div></tr>
				    <?php
				    $social_icons = array(
						"facebook"   => array("img" => "soci-1.gif"),
						"twitter"    => array("img" => "soci-2.gif"),
						"linkedin"   => array("img" => "soci-3.gif"),
						"pinterest"  => array("img" => "soci-4.gif"),
						"youtube"    => array("img" => "soci-5.gif"),
						"blog"       => array("img" => "soci-6.gif"),
						"googleplus" => array("img" => "soci-7.gif"),
				    	);

				    foreach($social_icons as $_icon => $_property){
				    	?>
				    	<tr>
	                        <td class="label">
							    <label for="<?php echo $_icon; ?>_url">
							        <input type="checkbox" value="1" <?php if(isset($cmsSettings['social_media'][$_icon]) && $cmsSettings['social_media'][$_icon] == '1'){ echo 'checked';}?>  name="social_media[<?php echo $_icon; ?>]"/>
							        <img alt="<?php echo $_icon; ?>" src="<?php echo $this->getSkinUrl('images/mobiadmin/'.$_property['img']); ?>">
							     </label>						
							</td>
	                        <td class="value"><input id="<?php echo $_icon; ?>_url" class="validate-url input-text" type="url" value="<?php echo $cmsSettings['social_media'][$_icon.'_url'] ?>" name="social_media[<?php echo $_icon; ?>_url]" placeholder="<?php echo $_icon; ?> URL"/></td>
						</tr>
				    	<?php
				    }
				    ?>
                </tbody>
             </table>
         </div>
	</div>

	<div class="entry-edit-head">
	    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('CMS Pages <span class="app-scope">[STORE VIEW]</span>')?></h4>
	</div>
	<div id="store_information" class="fieldset ">
	    <div class="hor-scroll">
            <table cellspacing="0" class="form-list">
                <tbody>
				    <?php if(sizeof($cmsPages) == '0'):?>
					   <?php for($page=1; $page <=7; $page++ ):?>
					   <?php $pageName = 'page_'.$page?>
					     <tr class="new-pages">
						     <td class="label"><label for="page<?php echo $page;?>"><?php echo $this->__('Page '.$page)?></label></td>
							 <td class="value"><label><?php echo $this->__('Active ')?></label><input type="checkbox" name="cms_pages[<?php echo $pageName?>][active]" value="" ></td>
						 </tr>
                         <tr class="new-pages">
						     <td  class="label"></td>
						     <td class="value"><input id="" class=" input-text" type="text" value="" name="cms_pages[<?php echo $pageName?>][page_title]" placeholder="<?php echo $this->__('Page Title')?>"/></td>
						 </tr>
						 <tr class="new-pages">
						     <td  class="label"></td>
						     <td class="value">
							     <div><?php echo $this->__('Link to external page:')?></div>
								 <input class="ext-yes" type="radio" name="cms_pages[<?php echo $pageName?>][link_to_external]" value="1"/><?php echo $this->__('Yes')?>
								 <input class="ext-no" type="radio" name="cms_pages[<?php echo $pageName?>][link_to_external]"  value="0"/><?php echo $this->__('No')?>
							 </td>
						 </tr>
						 <tr class="cms-url-content" style="display:none;">
						     <td  class="label"></td>
						     <td class="value"><input id="" class="validate-url  input-text" type="url" value="<?php echo ''; ?>" name="cms_pages[<?php echo $pageName?>][page_url]" /></td>
						 </tr> 
						 <tr class="cms-page-content">
						     <td  class="label"></td>
						     <td class="value"><textarea id="cms-page-content<?php echo $page ?>" class=" textarea" name="cms_pages[<?php echo $pageName?>][page_content]" value=""></textarea></td>
						 </tr>
					   <?php endfor;?>
					<?php endif;?>
				    <?php $pageNumber = 1; foreach ($cmsPages as $cmsPage):?>
					     <?php $pageIndex = 'page_'.$pageNumber;
						 $pageTitle = $cmsPages[$pageIndex]['page_title'];
						 $pageIsActive = isset($cmsPages[$pageIndex]['active'])?$cmsPages[$pageIndex]['active']:null;
						 $link_to_external = $cmsPages[$pageIndex]['link_to_external'];
						 ?>
					     <tr>
						     <td class="label"><label for="page<?php echo $pageNumber;?>"><?php echo $this->__('Page '.$pageNumber)?></label></td>
							 <td class="value"><label><?php echo $this->__('Active ')?></label><input type="checkbox" name="cms_pages[<?php echo $pageIndex?>][active]" class="" value="1" <?php if($pageIsActive == '1'){ echo 'checked';}?>>
							     
							 </td>
						 </tr>
                         <tr>
						     <td  class="label"></td>
						     <td class="value"><input id="" class=" input-text" type="text" value="<?php echo $pageTitle ?>" name="cms_pages[<?php echo $pageIndex?>][page_title]" placeholder="<?php echo $this->__('Page Title')?>"/></td>
						 </tr>
						 <tr>
						     <td  class="label"></td>
						     <td class="value">
							     <div><?php echo $this->__('Link to external page:')?></div>
								 <input class="ext-yes" type="radio" name="cms_pages[<?php echo $pageIndex?>][link_to_external]" <?php if($link_to_external=='1'){ echo 'checked';}?> value="1"/><?php echo $this->__('Yes')?>
								 
								 <input class="ext-no" type="radio" name="cms_pages[<?php echo $pageIndex?>][link_to_external]" <?php if($link_to_external=='0' || empty($link_to_external)){ echo 'checked';}?> value="0"/><?php echo $this->__('No')?>
							 </td>
						 </tr>						 
						 <tr class="cms-url-content" <?php if ($cmsPages[$pageIndex]['link_to_external'] == '0' || empty($link_to_external)){ echo "style='display:none;'"; } ?> >
						     <td  class="label"></td>
						     <td class="value"><input id="" class="validate-url  input-text" type="url" value="<?php echo $cmsPages[$pageIndex]['page_url']?>" name="cms_pages[<?php echo $pageIndex?>][page_url]"/></td>
						 </tr>						 
						 <tr class="cms-page-content" <?php if ($cmsPages[$pageIndex]['link_to_external'] == '1'){ echo "style='display:none;'"; } ?>>
						     <td  class="label"></td>
						     <td class="value"><textarea id="cms-page-content<?php echo $pageNumber ?>" class=" textarea" name="cms_pages[<?php echo $pageIndex?>][page_content]" value=""><?php echo $cmsPages[$pageIndex]['page_content']?></textarea></td>
						 </tr> 
						 
						 <?php $pageNumber++;?>
					<?php endforeach;?>
				</tbody>
			</table>
		</div>
    </div>
</div>
<script>
jQuery( document ).ready(function() {
	jQuery('.ext-yes').click(function(){   
	   //alert(jQuery(this).attr('name'));
	   var name = jQuery(this).attr('name');
	   name = name.replace('[link_to_external]','');
	   if(jQuery("textarea[name='"+name+"[page_content]']").length){
			jQuery("textarea[name='"+name+"[page_content]']").parent('td').parent('tr').hide();
			jQuery("input[name='"+name+"[page_url]']").parent('td').parent('tr').show();
	   }
	   //jQuery(this).parents('tr').next().css("display","table-row");
	   //jQuery(this).parents('tr').next().next().css("display","none");
	});

	jQuery('.ext-no').click(function(){   
	   //alert(jQuery(this).attr('name'));
	   //jQuery(this).parents('tr').next().css("display","none");
	   //jQuery(this).parents('tr').next().next().css("display","table-row");
	   var name = jQuery(this).attr('name');
	   name = name.replace('[link_to_external]','');
	   if(jQuery("textarea[name='"+name+"[page_content]']").length){
			jQuery("textarea[name='"+name+"[page_content]']").parent('td').parent('tr').show();
			jQuery("input[name='"+name+"[page_url]']").parent('td').parent('tr').hide();
	   }
	});

	
});
</script>

<script type="text/javascript">
window.onload=function()
{
   tinyMCE.init({
    mode : "exact",
    elements: "company_address,cms-page-content1,cms-page-content2,cms-page-content3,cms-page-content4,cms-page-content5,cms-page-content6,cms-page-content7",
    theme : "advanced",
    plugins : "inlinepopups,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras",
    theme_advanced_buttons1 : "newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
    theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
    theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
    theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,|,visualchars,nonbreaking",
    theme_advanced_toolbar_location : "top",
    theme_advanced_toolbar_align : "left",
    theme_advanced_path_location : "bottom",
    extended_valid_elements : "a[name|href|target|title|onclick],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name],hr[class|width|size|noshade],font[face|size|color|style],span[class|align|style]",
    theme_advanced_resize_horizontal : 'true',
    theme_advanced_resizing : 'true',
    apply_source_formatting : 'true',
    convert_urls : 'false',
    force_br_newlines : 'true',
    doctype : '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">'
  });
};
jQuery('#pushnotifications').attr("maxlength","255");
</script>



<script type="text/javascript">
    //< ![CDATA[
        var customForm = new VarienForm('edit_form');			
    //]]>
</script>