<?php
$iconSettings = Mage::helper('mobiadmin')->getCategoryIconSettings();
?>
<div class="entry-edit">
    <div class="entry-edit-head">
	    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Manage Category Icons <span class="app-scope">[Website]</span>')?></h4>
	</div>
	<div id="store_information" class="fieldset ">
	    <div class="hor-scroll">
            <table cellspacing="0" class="form-list icon-table">
                <tbody>
					<tr>
					   	<td class="label">
							<label for="chkIsMagentoCategoryThumbnail"><?php echo $this->__('Apply Magento Category Thumbnail to all categories')?></label>
						</td>
					   	<td class="value"><input type="checkbox" id="chkMagentoIcon" name="chkNoIcon" <?php if(isset($iconSettings['MAGENTO_CATEGORY_THUMBNAIL']) && $iconSettings['MAGENTO_CATEGORY_THUMBNAIL'] == '1') echo 'checked'; ?>></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>