<?php
$applicationData          = Mage::registry('application_data');
$applicationCode          = $applicationData->getAppCode();
$applicationKey           = $applicationData->getAppKey();
$applicationName          = $applicationData->getAppName();
$applicationCreatedTime   = $applicationData->getCreatedTime();
$applicationAndroidUrl    = $applicationData->getAndroidUrl();
$applicationIosUrl        = $applicationData->getIosUrl();
$applicationAndroidStatus = $applicationData->getAndroidStatus();
$applicationIosStatus     = $applicationData->getIosStatus();
$applicationCreatedTime   = strtotime($applicationCreatedTime);
$licenseType              = $applicationData->getAppMode();
$Submittedudid            = $applicationData->getUdid();
$mobileWebsiteUrl         = $applicationData->getWebappUrl();
$addonParams              = @unserialize($applicationData->getAddonParameters());

?>
<div class="overview entry-edit">
    <div class="entry-edit-head">
	    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('App Details <span class="app-scope">[Website]</span>')?></h4>
	</div>
	<table cellspacing="0" class="form-list">
		<tbody>
			<tr>
				<td class="label"><?php echo $this->__('App Name : ')?></td>
				<td class="value"><?php echo $applicationName?></td>
			</tr>
			<tr>
				<td class="label"><?php echo $this->__('App Key :')?></td>
				<td class="value"><?php echo $applicationKey;?></td>
			</tr>
			<tr>
				<td class="label"><?php echo $this->__('License Type :')?></td>
				<td class="value">
				    <span style="text-transform: capitalize;"><?php echo $licenseType.' Version '; ?></span>
					<?php if($licenseType == 'demo'):?>
					<a class="link-store-scope" title="<?php echo $this->__('Demo license contains all features but it is not authorized version to publish the app on app store. Buy the license and get this app on app stores')?>"  style="margin:0;"></a>		
						<button onclick="buynow.submit()" type="button"><?php echo $this->__('Buy Now')?></button>
					<?php endif;?>
				</td>
			</tr>
			<tr>
				<td class="label"><?php echo $this->__('Created Date :')?></td>
				<td class="value"><?php echo date('d-m-Y',$applicationCreatedTime);?></td>
			</tr>
		</tbody>
	</table>
	<?php if($licenseType == 'demo'):?>
	    <div class="entry-edit-head">
			<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Android App <span class="app-scope">[Website]</span>')?></h4>
		</div>
		<table cellspacing="0" class="form-list">
			<tbody>
			    <tr>
				    <td class="label"><?php echo $this->__('Android App Status :')?></td>
				    <td class="value">
					<?php if(!empty($applicationAndroidStatus)):?>
					    <?php echo $this->__($applicationAndroidStatus)?>
					<?php endif;?>
					</td>
			    </tr>
				<tr>
					<td class="label"><?php echo $this->__('Download Android App :')?></td>
					<td class="value">
					   <?php if(!empty($applicationAndroidUrl)):?>					       
					       <strong><?php echo $applicationAndroidUrl;?></strong>
						   <a href="#emailmeandroiddemourl" onclick="popupemail(this)" class="email-me-fancybox"><?php echo $this->__('Email me this URL')?></a>
						   <a class="qr-code-fancybox" onclick="popupqrcode(this)" href="#android-demo-app-qrcode" onclick="popupqrcode(this)"><?php echo $this->__('QR Code of this URL')?></a>
                           <div id="android-demo-app-qrcode" class="qr-code" style="display:none">
						       <div class="custom-overlay-close" onclick="closepopup(this)" style="display:none">X</div>
						       <img  src="<?php echo 'https://chart.googleapis.com/chart?cht=qr&chs=200x200&chl='.$applicationAndroidUrl.'&choe=UTF-8'?>"/>
						   </div>

						   <div id="emailmeandroiddemourl" class="emailmeparent" style="display:none;">
						       <div class="custom-overlay-close" onclick="closepopup(this)" style="display:none">X</div>
							   <input type="hidden" value="android" name="templatetype" class="templatetype"/>
						       <div class="label-email"><?php echo $this->__('Enter your Email Address ')?></div></br>
						       <input type="text" class="emailid" name="emailid" value=""/></br>
							   <input type="hidden" name="url" class="app-url"  value="<?php echo $applicationAndroidUrl;?>"/>
							   <?php echo $this->__('Android URL will be sent to this email address')?></br></br>
							   <a class="send-email" onclick="emailme(this)"><?php echo $this->__('Send Email')?></a>
						   </div>
					   <?php endif;?>
					</td>
				</tr>
				<tr>	
					<?php if(!empty($applicationAndroidUrl)):?>
					<td colspan ="2">
						<span><?php echo $this->__('Open the above URL in your android phone browser, it will download the mobile app in your mobile device')?></span><br>
						<span><?php echo $this->__('If you have any mobicommerce demo app installed in your mobile device please uninstall that before installing a new mobicommerce demo app')?></span>
					</td>
					<?php endif;?>
				</tr>
			</tbody>
		</table>
		<?php if($Submittedudid == ''): ?>
		<div class="entry-edit-head">
			<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('iOS App <span class="app-scope">[Website]</span>')?></h4>
		</div>
		
		<table cellspacing="0" class="form-list">
			<tbody>
			    <tr>
					<td colspan ="2">
						<span><?php echo $this->__('Please provide UDID of your iOS device (iPhone and iPad), to preview the iOS demo app')?></span>
					</td>
				</tr>
				<tr>
					<td class="label"><?php echo $this->__('UDID of your iOS devices (iPhone and iPad) :')?></td>
					<td class="value">
					    <input type="text" class="input-text validate-for-udid" name="udid" />
						<br><small><?php echo $this->__('In case of Multiple UDID, enter them comma separated.')?></small>
					</td>
				</tr>				
			</tbody>
		</table>
		<?php endif;?>
		<?php if(!empty($Submittedudid)):?>
		<div class="entry-edit-head">
			<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('iOS App <span class="app-scope">[Website]</span>')?></h4>
		</div>
		<table cellspacing="0" class="form-list">
			<tbody>
				<tr>
					<td class="label"><?php echo $this->__('iOS App Status :')?></td>
					<td class="value">
                       <?php if(!empty($applicationIosStatus)):?>
					       <?php echo $this->__($applicationIosStatus);?>					   
					   <?php endif;?>
					</td>
				</tr>
				<tr>
					<td class="label"><?php echo $this->__('Download iOS App :')?></td>
					<td class="value">
					   <?php if(empty($applicationIosUrl)):?>
					       <?php echo $this->__('Url will be Updated as soon as the app ready to download')?>
					   <?php else:?>
					       <strong><?php echo $applicationIosUrl;?></strong>
						   <a href="#emailmeiosdemourl" class="email-me-fancybox" onclick="popupemail(this)" ><?php echo $this->__('Email me this URL')?></a>
						   <a class="qr-code-fancybox" onclick="popupqrcode(this)" href="#ios-demo-app-qrcode"><?php echo $this->__('QR Code of this URL')?></a>
						   <div id="ios-demo-app-qrcode" style="display:none" class="qr-code">
							   <div class="custom-overlay-close" onclick="closepopup(this)" style="display:none">X</div>
							   <img src="<?php echo 'https://chart.googleapis.com/chart?cht=qr&chs=200x200&chl='.$applicationIosUrl.'&choe=UTF-8'?>"/>
						   </div>
						   <div id="emailmeiosdemourl" style="display:none;" class="emailmeparent">
						       <div class="custom-overlay-close" onclick="closepopup(this)" style="display:none">X</div>
							   <input type="hidden" value="ios" name="templatetype" class="templatetype"/>
						       <div class="label-email"><?php echo $this->__('Enter your Email Address ')?></div></br>
						       <input type="text" class="emailid" name="emailid" value=""/></br>
							   <input type="hidden" name="url" class="app-url" value="<?php echo $applicationIosUrl;?>"/>
							   <?php echo $this->__('iOS URL will be sent to this email address')?></br>
							   <a class="send-email" onclick="emailme(this)"><?php echo $this->__('Send Email')?></a>
						   </div>
					   <?php endif;?>
					</td>
				</tr>
				<tr>	
					<?php if(!empty($applicationIosUrl)):?>
					<td colspan ="2">
						<span><?php echo $this->__('Open the above URL in your iPhone browser, it will download the mobile app in your mobile device')?></span><br>
						<span><?php echo $this->__('If you have any mobicommerce demo app installed in your mobile device please uninstall that before installing a new mobicommerce demo app')?></span>
					</td>
					<?php endif;?>
				</tr>
				<tr>
					<td class="label"><?php echo $this->__('Submitted UDID :')?></td>
					<td class="value"><?php  echo str_replace(",","<br>",$Submittedudid);?></td>
				</tr>
				<?php if(!empty($Submittedudid) && empty($applicationIosUrl)):?>
				<tr>
					<td colspan ="2">
						<span><?php echo $this->__('Your iOS demo app is still under process soon we will provide you iOS app for provided UDID')?></span>
					</td>
				</tr>
				<?php endif;?>
			</tbody>
		</table>
		<?php endif;?>
		<div class="entry-edit-head">
			<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Mobile Website <span class="app-scope">[Website]</span>')?></h4>
		</div>
		<table cellspacing="0" class="form-list">
			<tbody>
				<tr>
					<td class="label"><?php echo $this->__('Mobile Website URL :')?></td>
					<td class="value">
					     <div class="url">
						 <strong><?php echo $mobileWebsiteUrl; ?></strong>
						 <a href="#mobilewebdemourl" onclick="popupemail(this)" class="email-me-fancybox"><?php echo $this->__('Email me this URL')?></a>
					     <a class="qr-code-fancybox" onclick="popupqrcode(this)" href="#mobileweb-demo-app-qrcode"><?php echo $this->__('QR Code of this URL')?></a>
						 <div id="mobileweb-demo-app-qrcode" class="qr-code" style="display:none">
							 <div class="custom-overlay-close" onclick="closepopup(this)" style="display:none">X</div>
							 <img  src="<?php echo 'https://chart.googleapis.com/chart?cht=qr&chs=200x200&chl='.$mobileWebsiteUrl.'&choe=UTF-8'?>"/>
						 </div>
					     <div id="mobilewebdemourl" style="display:none;" class="emailmeparent">
						     <div class="custom-overlay-close" onclick="closepopup(this)" style="display:none">X</div>
							 <input type="hidden" value="website" name="templatetype" class="templatetype"/>
						     <div class="label-email"><?php echo $this->__('Enter your Email Address ')?></div></br>
						     <input type="text" class="emailid" name="emailid" value=""/></br>
						     <input type="hidden" name="url" class="app-url" value="<?php echo $mobileWebsiteUrl;?>"/>
						     <?php echo $this->__('Mobile Website URL will be sent to this email address')?></br>
						     <a class="send-email" onclick="emailme(this)"><?php echo $this->__('Send Email')?></a>
					     </div>						 					 
					</td>
				</tr>
                <tr>
					<td colspan="2"><?php echo $this->__('This Mobile website created by mobicommerce is currently hosted on our server, once you purchase its license it will be delivered to your server.')?></td>
					<td></td>
				</tr>				
			</tbody>
		</table>
	<?php endif;?>
	<?php if($licenseType == 'live'):?>
	    <div class="entry-edit-head">
			<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Android App Deliverables <span class="app-scope">[Website]</span>')?></h4>
		</div>
		<table cellspacing="0" class="form-list">
			<tbody>
			    <tr>
				    <td class="label"><?php echo $this->__('Android Status :')?></td>
				    <td class="value"><?php echo $this->__($applicationAndroidStatus)?></td>
			    </tr>
				<tr>
					<td class="label"><?php echo $this->__('Download Android Deliverables :')?></td>
					<td class="value">
					    <?php if(!empty($applicationAndroidUrl)):?>
					       <strong><?php echo $applicationAndroidUrl;?></strong>
						   <a href="#emailmeandroidliveurl" class="email-me-fancybox" onclick="popupemail(this)"><?php echo $this->__('Email me this URL')?></a>
						   <a class="qr-code-fancybox" onclick="popupqrcode(this)" href="#android-live-app-qrcode"><?php echo $this->__('QR Code of this URL')?></a>
						   <div id="android-live-app-qrcode" class="qr-code" style="display:none">
							   <div class="custom-overlay-close" onclick="closepopup(this)" style="display:none">X</div>
							   <img src="<?php echo 'https://chart.googleapis.com/chart?cht=qr&chs=200x200&chl='.$applicationAndroidUrl.'&choe=UTF-8'?>"/>
						   </div>
						   <div id="emailmeandroidliveurl" style="display:none;" class="emailmeparent">
						       <div class="custom-overlay-close" onclick="closepopup(this)" style="display:none">X</div>
							   <input type="hidden" value="android" name="templatetype" class="templatetype"/>
						       <div class="label-email"><?php echo $this->__('Enter your Email Address ')?></div></br>
						       <input type="text" class="emailid" name="emailid" value=""/></br>
							   <input type="hidden" name="url" class="app-url" value="<?php echo $applicationAndroidUrl;?>"/>
							   <?php echo $this->__('Android URL will be sent to this email address')?></br>
							   <a class="send-email" onclick="emailme(this)"><?php echo $this->__('Send Email')?></a>
						   </div>
						<?php else:?>
						    <span><?php echo $this->__('It will take 2-3 days to prepare your deliverables.') ?></span>
					    <?php endif;?>
					</td>
				</tr>
			</tbody>
		</table>
		<div class="entry-edit-head">
			<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('iOS App Deliverables <span class="app-scope">[Website]</span>')?></h4>
		</div>
		<table cellspacing="0" class="form-list">
			<tbody>
			    <tr>
					<td class="label"><?php echo $this->__('iOS App Status :')?></td>
					<td class="value">
                       <?php if(!empty($applicationIosStatus)):?>
					       <?php echo $this->__($applicationIosStatus);?>					   
					   <?php endif;?>
					</td>
				</tr>
				<tr>
					<td class="label"><?php echo $this->__('Download iOS Deliverables :')?></td>
					<td class="value">
					   <?php if(empty($applicationIosUrl)):?>
					       <span><?php echo $this->__('It will take 2-3 days to prepare your deliverables.') ?></span>
					   <?php else:?>
					       <strong><?php echo $applicationIosUrl;?></strong>
						   <a href="#emailmeiosliveurl" class="email-me-fancybox" onclick="popupemail(this)"><?php echo $this->__('Email me this URL')?></a>
						   <a class="qr-code-fancybox" onclick="popupqrcode(this)" href="#ios-live-app-qrcode"><?php echo $this->__('QR Code of this URL')?></a>
						   <div id="ios-live-app-qrcode" class="qr-code" style="display:none">
							   <div class="custom-overlay-close" onclick="closepopup(this)" style="display:none">X</div>
							   <img  src="<?php echo 'https://chart.googleapis.com/chart?cht=qr&chs=200x200&chl='.$applicationIosUrl.'&choe=UTF-8'?>"/>
						   </div>
						   <div id="emailmeiosliveurl" style="display:none;" class="emailmeparent">
						       <div class="custom-overlay-close" onclick="closepopup(this)" style="display:none">X</div>
							   <input type="hidden" value="ios" name="templatetype" class="templatetype"/>
						       <div class="label-email"><?php echo $this->__('Enter your Email Address ')?></div></br>
						       <input type="text" class="emailid" name="emailid" value=""/></br>
							   <input type="hidden" name="url" class="app-url" value="<?php echo $applicationIosUrl;?>"/>
							   <?php echo $this->__('iOS URL will be sent to this email address')?></br>
							   <a class="send-email" onclick="emailme(this)"><?php echo $this->__('Send Email')?></a>
						   </div>
					   <?php endif;?>
					</td>
				</tr>
				<tr>	
					<?php if(!empty($applicationIosUrl)):?>
					<td colspan ="2">
						<span><?php echo $this->__('Open the above URL in your iPhone browser, it will download the mobile app in your mobile device')?></span><br>
						<span><?php echo $this->__('If you have any mobicommerce demo app installed in your mobile device please uninstall that before installing a new mobicommerce demo app')?></span>
					</td>
					<?php endif;?>
				</tr>
			</tbody>
		</table>
		<?php 
		$services_purchased = isset($addonParams['services_purchased']) ? $addonParams['services_purchased'] : NULL;

		if(empty($services_purchased))
			$services_purchased = array();
		
		?>
		<?php if(!in_array('mobilewebsite', $services_purchased) && !in_array('webapps', $services_purchased)):?>


       <div class="entry-edit-head">
			<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Mobile Website <span class="app-scope">[Website]</span>')?></h4>
		</div>
		<table cellspacing="0" class="form-list">
			<tbody>
				<tr>
					<td class="label"><?php echo $this->__('Mobile Website URL :')?></td>
					<td class="value">
					     <div class="url">
						 <strong><?php echo $mobileWebsiteUrl; ?></strong>
						 <a href="#mobilewebdemourl" onclick="popupemail(this)" class="email-me-fancybox"><?php echo $this->__('Email me this URL')?></a>
					     <a class="qr-code-fancybox" onclick="popupqrcode(this)" href="#mobileweb-demo-app-qrcode"><?php echo $this->__('QR Code of this URL')?></a>
						 <div id="mobileweb-demo-app-qrcode" class="qr-code" style="display:none">
							 <div class="custom-overlay-close" onclick="closepopup(this)" style="display:none">X</div>
							 <img  src="<?php echo 'https://chart.googleapis.com/chart?cht=qr&chs=200x200&chl='.$mobileWebsiteUrl.'&choe=UTF-8'?>"/>
						 </div>
					     <div id="mobilewebdemourl" style="display:none;" class="emailmeparent">
						     <div class="custom-overlay-close" onclick="closepopup(this)" style="display:none">X</div>
							 <input type="hidden" value="website" name="templatetype" class="templatetype"/>
						     <div class="label-email"><?php echo $this->__('Enter your Email Address ')?></div></br>
						     <input type="text" class="emailid" name="emailid" value=""/></br>
						     <input type="hidden" name="url" class="app-url" value="<?php echo $mobileWebsiteUrl;?>"/>
						     <?php echo $this->__('Mobile Website URL will be sent to this email address')?></br>
						     <a class="send-email" onclick="emailme(this)"><?php echo $this->__('Send Email')?></a>
					     </div>						 					 
					</td>
				</tr>
                <tr>
					<td colspan="2"><?php echo $this->__('This Mobile website created by mobicommerce is currently hosted on our server, once you purchase its license it will be delivered to your server.')?></td>
					<td></td>
				</tr>
				<tr>
					<td></td>
					<td colspan="2">
						<button onclick="buynowwebsite.submit()" type="button"><?php echo $this->__('Buy Now')?></button>
					</td>
				</tr>
			</tbody>
		</table>

		<?php else:?>
		<div class="entry-edit-head">
			<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Mobile Website Deliverables <span class="app-scope">[Website]</span>')?></h4>
		</div>
		<table cellspacing="0" class="form-list">
			<tbody>
				<tr>
					<td class="label"><?php echo $this->__('Download Mobile Website Deliverables :')?></td>
					<td class="value">
					     <?php if(!empty($mobileWebsiteUrl)): ?>
					     <div class="url"><strong><?php echo $mobileWebsiteUrl; ?></strong></div>	<a href="#emailmewebsiteliveurl" class="email-me-fancybox" onclick="popupemail(this)"><?php echo $this->__('Email me this URL')?></a>
						   <a class="qr-code-fancybox" onclick="popupqrcode(this)" href="#website-live-app-qrcode"><?php echo $this->__('QR Code of this URL')?></a>
						   <div id="website-live-app-qrcode" class="qr-code" style="display:none">
							   <div class="custom-overlay-close" onclick="closepopup(this)" style="display:none">X</div>
							   <img src="<?php echo 'https://chart.googleapis.com/chart?cht=qr&chs=200x200&chl='.$mobileWebsiteUrl.'&choe=UTF-8'?>"/>
						   </div>
						   <div id="emailmewebsiteliveurl" style="display:none;" class="emailmeparent">
						       <div class="custom-overlay-close" onclick="closepopup(this)" style="display:none">X</div>
							   <input type="hidden" value="website" name="templatetype" class="templatetype"/>
						       <div class="label-email"><?php echo $this->__('Enter your Email Address ')?></div></br>
						       <input type="text" class="emailid" name="emailid" value=""/></br>
							   <input type="hidden" name="url" class="app-url" value="<?php echo $mobileWebsiteUrl;?>"/>
							   <?php echo $this->__('Mobile Website URL will be sent to this email address')?></br></br>
							   <a class="send-email" onclick="emailme(this)"><?php echo $this->__('Send Email')?></a>
						   </div>
						   <?php else:?>
                                <span><?php echo $this->__('It will take 2-3 days to prepare your deliverables.') ?></span>
						   <?php endif;?>
					</td>
				</tr>		
			</tbody>
		</table>
		<?php endif;?>
	<?php endif;?>
</div>
<div class="custom-overlay" style="display:none"></div>
<script>
    Validation.add('validate-for-udid','Please Insert 40 Charecters udid!',function(the_field_value){		
		if(!checkudid(the_field_value)){
            return false;
		}
		return true;
    });
	function checkudid(udids)
    {
	   var validated = true;
	   var parseudids = udids.split(',');
       parseudids.each(function(key){
		   if(key.length && key.trim().length != 40){
			   validated = false;
		   }
	   });
	   return validated;
    }
	function emailme(e)
	{
		var emailid = jQuery(e).parents('.emailmeparent').find('.emailid').val();
		var appurl = jQuery(e).parents('.emailmeparent').find('.app-url').val();
		var templatetype = jQuery(e).parents('.emailmeparent').find('.templatetype').val();
		if(emailid == '') {
            alert('Please Insert Email Id First');
		} else{
			if(appurl !='')
			{
				if(IsEmail(emailid)) {
					new Ajax.Request("<?php echo Mage::getUrl('mobicommerce/index/sendemail')?>", {
						method: 'Post',
						parameters: {emailid : emailid, appurl : appurl, templatetype : templatetype},
						onComplete: function(data) {				    
						},
						onSuccess: function(response){
							var json = response.responseText.evalJSON(true);
							if(json.status == 'success'){
								console.log(json.success);
								alert(json.success);
								jQuery('.custom-overlay').hide();
								jQuery('.custom-overlay-close').hide();
								jQuery('.qr-code').removeClass('popup-qr-code');
								jQuery('.custom-overlay-close').removeClass('close-wrapper');
								jQuery('.emailmeparent').removeClass('popup-email');
							}
							else{
								alert(json.error);
							}
						},
						onFailure: function(response){
							var json = response.responseText.evalJSON(true);
							alert(json.error);
						}

					});
				} 
				else
				{
					alert('Please Insert Valid Email Id!');
				}
			}
		}
        
	}
	function popupqrcode(e)
	{
		var target = jQuery(e).attr('href');
		jQuery(target).addClass('popup-qr-code');
		jQuery('.custom-overlay').show();
		jQuery(target).find('.custom-overlay-close').show();
		jQuery(target).find('.custom-overlay-close').addClass('close-wrapper').show();
	}

	function closepopup(e)
	{
        jQuery('.custom-overlay').hide();
		jQuery('.custom-overlay-close').hide();
		jQuery('.qr-code').removeClass('popup-qr-code');
		jQuery('.custom-overlay-close').removeClass('close-wrapper');
		jQuery('.emailmeparent').removeClass('popup-email');
	}

	function popupemail(e)
	{
		var targetpoup = jQuery(e).attr('href');
        jQuery(targetpoup).addClass('popup-email');
		jQuery('.custom-overlay').show();
		jQuery('.custom-overlay-close').show();
		jQuery('.custom-overlay-close').addClass('close-wrapper').show();
	}
	function IsEmail(email) {
	  var regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;
	  return regex.test(email);
	}
</script>