<?php
$productCollection = Mage::helper('mobiadmin')->getProductCollectionForSlider();
$sliderCollection = Mage::helper('mobiadmin')->getProductSliderCollection();
?>

<div class="entry-edit">
    <div class="entry-edit-head">
	    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Product Slider <span class="app-scope">[STORE VIEW]</span>')?></h4>
	</div>
	<div id="store_information" class="fieldset">
	    <div class="hor-scroll">
            <table cellspacing="0" class="form-list">
                <tbody>
                    <?php foreach ($sliderCollection as $slider):
						$sliderLabel      = $slider->getSliderLabel();
						$sliderCode       = $slider->getSliderCode();
						$sliderPosition   = $slider->getSliderPosition();
						$sliderSettings   = $slider->getSliderSettings();
						$sliderSettings   = Mage::helper('mobiadmin')->_jsonUnserialize($sliderSettings);
						$sliderNoOfDays   = $sliderSettings['no_of_days'];
						$sliderStatus     = $slider->getSliderStatus();
						$sliderProductIds = $slider->getData('slider_productIds');
						$sliderProductIds = explode(",",$sliderProductIds);
						$sliderProductIds = array_combine(range(1, count($sliderProductIds)), array_values($sliderProductIds));
						?>
						<tr>
						    <td class="value"><input id="<?php echo $sliderCode; ?>" class=" input-text" type="text" value="<?php echo $sliderLabel; ?>" name="<?php echo $sliderCode.'-slider-name';?>"/></td>
							<td class="value"><?php echo $this->__('Position:') ?><input id="<?php echo $sliderCode; ?>" class="" type="text" value="<?php echo $sliderPosition; ?>" name="<?php echo $sliderCode.'-slider-position';?>"/></td>
						    <td class="value"><?php echo $this->__('Active:') ?><input id="<?php echo $sliderCode; ?>" class="" type="checkbox" value="1" name="<?php echo $sliderCode.'-slider-status';?>" <?php if($sliderStatus == '1'){ echo 'checked';}?>/></td>
						</tr>
						<?php if($sliderCode=='featured-products' || $sliderCode=='best-collection' || $sliderCode=='new-arrivals' || $sliderCode=='best-sellers'):?>
	                        <?php for($product=1; $product<='10'; $product++): ?>
							    <tr>
								    <td class="label"><?php echo $this->__('Product '.$product)?></td>
									<td class="value">
									    <select name="<?php echo $sliderCode ?>[product][<?php echo $product; ?>]">
											<option value=""><?php echo $this->__('Please Select');?></option>
									     	<?php foreach($productCollection as $productData): ?>
	                                         	<option value="<?php echo $productData->getId();?>" <?php if(isset($sliderProductIds[$product]) && ( $sliderProductIds[$product] == $productData->getId())){ echo 'selected';}?>><?php echo $productData->getName();?></option>
										 	<?php endforeach; ?>
										</select>
									</td>
								</tr>
							<?php endfor;?>
						<?php elseif($sliderCode=='best-sellers-automated'): ?>
	                        <tr>
							    <td class="label"></td>
								<td class="label"></td>
							    <td class="value"><span><?php echo $this->__('No.');?></span><input type="text" name="<?php echo $sliderCode;?>[no_of_days]" value="<?php echo $sliderNoOfDays;?>"/><?php echo $this->__('days')?></td>
							</tr>
						<?php endif;
					endforeach; ?>
				</tbody>
			</table>
		</div>
	</div>
</div>