<div class="support-column">
	<img src="<?php echo $this->getSkinUrl('images/mobiadmin/needhelp.gif')?>" />
    <ul>
    	<li><a target="_blank" href="http://mobi-commerce.net/" class="live-support"><img src="<?php echo $this->getSkinUrl('images/mobiadmin/sup-1.png')?>" /><?php echo $this->__('Live Support')?></a></li>
        <li><img src="<?php echo $this->getSkinUrl('images/mobiadmin/sup-2.png')?>" class="contact-icon"/>+1-347-979-7106 (GMT +5.5)</li>
        <li><a target="_top" href="mailto:support@mobi-commerce.net"><img src="<?php echo $this->getSkinUrl('images/mobiadmin/sup-3.png')?>" class="email-icon"/>support@mobi-commerce.net</a></li>
        <li><a target="_blank" href="http://support.mobi-commerce.net/"><img src="<?php echo $this->getSkinUrl('images/mobiadmin/sup-4.png')?>" class="email-icon"/>support.mobi-commerce.net/</a></li>
    </ul>
</div>