<?php
$bannerData = Mage::registry('widgetdata');
$widget_status  = $bannerData['widget_status'];
$slider_widget_data = unserialize($bannerData['widget_data']);
$banners = $slider_widget_data['banners'];
//echo '<pre>'; print_r($banners); echo '</pre>';
$_htmlName = 'banner';
$_htmlId = "bannercontainer";
?>
<tr>
	<td class="label"><?php echo $this->__('Slider Images'); ?></td>
	<td colspan="10" class="grid" width="650">
		<table cellspacing="0" class="data border" id="<?php echo $_htmlName ?>_table">
			<col/>			
			<thead>
				<tr class="headings">
					<th><?php echo $this->__('Image') ?></th>
					<th><?php echo $this->__('Position') ?></th>
					<th><?php echo $this->__('Status') ?></th>
					<th><?php echo $this->__('Link To') ?></th>
					<th><?php echo $this->__('Action') ?></th>
				</tr>
			</thead>
			<tbody id="<?php echo $_htmlId ?>_container"></tbody>
			<tfoot>
				<tr>
					<td><?php echo $this->__('Recommended image width: 1080px') ?></td>
					<td colspan="4" class="a-right"><?php echo $this->getAddButtonHtml() ?></td>
				</tr>
			</tfoot>
		</table>
		<script type="text/javascript">
			//<![CDATA[
			var <?php echo $_htmlName ?>RowTemplate = 
				'<tr>'		
			        + '<input type="hidden" name="widget[widget_data][banners][{{index}}][<?php echo $_htmlName ?>_options]" id="<?php echo $_htmlName ?>_row_{{index}}_options" />'        
					+ '<td>'
						+'<input class="<?php echo $_htmlClass ?>" type="file" name="banners[{{index}}]" id="<?php echo $_htmlName ?>_row_{{index}}_name"/>'
								+'<div class="store-pickup-image">'
									+ '<img id="<?php echo $_htmlName ?>_row_{{index}}_image" src="" width="22px" height="22px" style="margin-left:5px;">'
								+'</div>'
								+ '<input id="<?php echo $_htmlName ?>_row_{{index}}_url" type="hidden" name="widget[widget_data][banners][{{index}}][<?php echo $_htmlName ?>_url]">'
					+ '</td>'            
			        + '<td>'
			             + '<input class="input-text" style="width:50px;" id="<?php echo $_htmlName ?>_row_{{index}}_position" type="text" name="widget[widget_data][banners][{{index}}][<?php echo $_htmlName ?>_position]">'
			        + '</td>' 
					+ '<td>'
			             + '<input style="width:50px;" id="<?php echo $_htmlName ?>_row_{{index}}_status" type="checkbox" value="1" name="widget[widget_data][banners][{{index}}][<?php echo $_htmlName ?>_status]">'
			        + '</td>' 
					+ '<td>'
			             + '<input  style="width:50px;" id="<?php echo $_htmlName; ?>_row_{{index}}_link" type="hidden">'
			             + '<input style="width:125px;" id="<?php echo $_htmlName ?>_row_link_{{index}}" type="text" class="input-text" name="widget[widget_data][banners][{{index}}][<?php echo $_htmlName; ?>_link]" readonly/>'
						 + '<a id="category_link" attr-bannerid ="{{index}}" href="javascript:void(0)"  value="Test popup dialog" onclick="showPopup(this);"><img src="<?php echo $this->getSkinUrl("images/rule_chooser_trigger.gif")?>" alt="" class="v-middle rule-chooser-trigger" title="Select Link"></a>'
			        + '</td>' 
					+ '<td class="last">'
						+ '<input type="hidden" name="widget[widget_data][banners][{{index}}][<?php echo $_htmlName ?>_delete]" class="delete" value="0" id="<?php echo $_htmlName ?>_row_{{index}}_delete" />'
						+ '<button title="<?php echo $this->__("Delete"); ?>" type="button" class="scalable delete icon-btn" id="<?php echo $_htmlName ?>_row_{{index}}_delete_button" onclick="return <?php echo $_htmlName ?>Control.deleteItem(event);">'
							+ '<span><?php echo $this->__("Delete") ?></span>'
						+ '</button>'
					+ '</td>'
				+ '</tr>';
			var <?php echo 'banner' ?>Control = {
				template: new Template(<?php echo $_htmlName; ?>RowTemplate, new RegExp('(^|.|\\r|\\n)({{\\s*(\\w+)\\s*}})', "")),
				itemsCount: 1,
				addItem: function(){
					var data = {
						id: 0,			
						position: 0,                      
						index: this.itemsCount,
						del: 0,
						banner_url:'',
						store:''
					};
					
					if (arguments.length >= 1) {
						data.banner_url = arguments[0];
						data.banner_position = arguments[1];
						data.banner_status = arguments[2];
						data.banner_link = arguments[3];
						this.itemsCount = data.index;
					}
					Element.insert($('<?php echo $_htmlId ?>_container'),{
						bottom: this.template.evaluate(data)
					});                
					$('<?php echo $_htmlName ?>_row_' + data.index + '_position').value = data.position;               
					$('<?php echo $_htmlName ?>_row_' + data.index + '_options').value = data.index;
					$('<?php echo $_htmlName ?>_row_' + data.index + '_delete').value = data.del;
					if ( data.banner_url != ''){
						if (typeof data.banner_url !== "undefined") {
							 url = data.banner_url;
							 $('<?php echo $_htmlName ?>_row_' + data.index + '_image').show();
							 $('<?php echo $_htmlName ?>_row_' + data.index + '_image').setAttribute('src',url);
							 $('<?php echo $_htmlName ?>_row_' + data.index + '_url').value = data.banner_url;
							 $('<?php echo $_htmlName ?>_row_link_' + data.index ).value = data.banner_link;
						}else{
							$('<?php echo $_htmlName ?>_row_' + data.index + '_image').setAttribute('src','');
							$('<?php echo $_htmlName ?>_row_' + data.index + '_image').hide();
						}	
					}
					else {
						$('<?php echo $_htmlName ?>_row_' + data.index + '_image').setAttribute('src','');
						$('<?php echo $_htmlName ?>_row_' + data.index + '_image').hide();
					}
					if (data.banner_status == 1){
						$('<?php echo $_htmlName ?>_row_' + data.index + '_status').checked = true;
					}
					if(data.banner_position !=''){
						if (typeof data.banner_position !== "undefined") {
							$('<?php echo $_htmlName ?>_row_' + data.index + '_position').value = data.banner_position;
						}else{
							$('<?php echo $_htmlName ?>_row_' + data.index + '_position').value = '0';
						}
					}
					this.itemsCount++;
				},
				disableElement: function(el){
					el.disabled = true;
					el.addClassName('disabled');
				},
				deleteItem: function(event){
					var tr = Event.findElement(event, 'tr');
					if (tr){
						Element.select(tr, '.delete').each(function(elem){elem.value='1'});
						Element.select(tr, ['input','select']).each(function(elem){elem.hide()});
						Element.hide(tr);
						Element.addClassName(tr, 'no-display template');
					}
					return false;
				}
			};
			<?php if(count($banners)): ?>
				<?php 
				$image = '';
				usort($banners, function($a, $b) {
					return $a['banner_position'] - $b['banner_position'];
				});
				foreach ($banners as $_item):?>
					<?php if($_item['banner_delete'] != 1):?>
						<?php echo $_htmlName ?>Control.addItem(
						    "<?php echo $_item['banner_url']; ?>",
							"<?php echo $_item['banner_position']; ?>",
							"<?php echo $_item['banner_status']; ?>",
							"<?php echo $_item['banner_link']; ?>"
							);
					<?php endif;?>
				<?php endforeach;?>
			<?php endif;?>
			//]]>
			var cat = "<?php echo Mage::app()->getRequest()->getParam('cat', false); ?>";
			function showPopup(e) {
				var bannerid = jQuery(e).attr("attr-bannerid");
				var bannersel = "#banner_row_link_"+bannerid;
				var linkval = jQuery(bannersel).val();
				sUrl ="<?php echo Mage::helper('adminhtml')->getUrl('mobiadmin2/widget/deeplink')?>bannerid/"+bannerid+'/link/'+linkval+'/cat/'+cat;
			    oPopup = new Window({
			        id:'popup_window1',
			        className: 'magento',
			        url: sUrl,
			        width: 820,
			        height: 600,
			        minimizable: false,
			        maximizable: false,
			        showEffectOptions: {
			            duration: 0.4
			        },
			        hideEffectOptions:{
			            duration: 0.4
			        },
			        destroyOnClose: true
			    });
			    oPopup.setZIndex(100);
			    oPopup.showCenter(true);
			}

			function closePopup() {
			    Windows.close('popup_window1');
			}
		</script>
	</td>
</tr>