<?php
$htmlData = Mage::registry('widgetdata');
$widget_status  = $htmlData['widget_status'];
$widget_label  = $htmlData['widget_label'];
$html_widget_data = unserialize($htmlData['widget_data']);
?>
<?php if($htmlData['widget_id']):?>
	<input type="hidden" name="widget_id" value="<?php echo $htmlData['widget_id']?>"/>
<?php endif;?>
<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend">HTML Content Widget</h4>
	</div>
</div>
<div class="fieldset">
	<table class="htmlcontent-widget-content form-list" cellspacing="0">
		<tbody>
			<tr>
				<td class="label"><label for=""></label></td>
				<td class="value">
				</td>
			</tr>
			<tr>
				<td class="label"><label for=""><?php echo $this->__('Name')?><span class="required">*</span></label></td>
				<td class="value">
					<input type="text" class="input-text required-entry" value="<?php if(!empty($widget_label)) echo $widget_label;?>" name="widget[name]"/>
				</td>
			</tr>
			<tr>
				<td class="label"><label for=""><?php echo $this->__('Title')?></label></td>
				<td class="value">
					<input type="text" class="input-text" value="<?php if(!empty($html_widget_data['title'])) echo $html_widget_data['title'];?>" name="widget[widget_data][title]"/>
				</td>
			</tr>
			<?php $widget_title_align = $html_widget_data['title_align'];?>
			<tr>
				<td class="label"><label for=""><?php echo $this->__('Align Title')?></label></td>
				<td class="value">
					<select name="widget[widget_data][title_align]">
						<option value="center" <?php if($widget_title_align == 'center') echo "selected"?>>Center</option>
						<option value="left" <?php if($widget_title_align == 'left') echo "selected"?>>Left</option>
						<option value="right" <?php if($widget_title_align == 'right') echo "selected"?>>Right</option>
					</select>
				</td>
			</tr>
			<tr>
				<td class="label"><label for=""><?php echo $this->__('Content')?></label></td>
				<td class="value">
					 <textarea id="htmlcontent" class="" rows="8" cols="50" name="widget[widget_data][htmlcontent]"><?php if(!empty($html_widget_data['htmlcontent'])) echo $html_widget_data['htmlcontent'];?></textarea>
				</td>
			</tr>
			<tr>
				<td class="label"><label for=""><?php echo $this->__('Status')?></label></td>
				<td class="value">
					 <select name="widget[enable]">
						 <option <?php if($widget_status == 0) echo "selected"?> value="0"><?php echo $this->__('No')?></option>
						 <option <?php if($widget_status == 1) echo "selected"?> value="1"><?php echo $this->__('Yes')?></option>
					 </select>
				</td>
			</tr>
		</tbody>
	</table>
</div>