<?php 
$applicationData = Mage::registry('application_data');
$applicationCode = $applicationData->getAppCode();
$applicationName = $applicationData->getAppName();
$applicationKey = $applicationData->getAppKey();
$applicationStoreId = $applicationData->getAppStoreid();
$storerooturl = Mage::app()->getStore($applicationStoreId)->getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK);
$themename = Mage::helper('mobiadmin')->getThemeName($applicationCode);
?>
<form target="_blank" name="buynow" id="buynow" action="<?php echo Mage::helper('mobiadmin')->buyNowUrl()?>" method="post">
<input type="hidden" name="app_name" value="<?php echo $applicationName;?>"/>
<input type="hidden" name="app_preview_code" value="<?php echo $applicationKey;?>"/>
<input type="hidden" name="app_code" value="<?php echo $applicationCode;?>"/>
<input type="hidden" name="selectedapp" value="nativeapps"/>
<input type="hidden" name="store_rooturl" value="<?php echo $storerooturl;?>"/>
</form>

<form target="_blank" name="buynowwebsite" id="buynowwebsite" action="<?php echo Mage::helper('mobiadmin')->buyNowUrl()?>" method="post">
<input type="hidden" name="app_name" value="<?php echo $applicationName;?>"/>
<input type="hidden" name="app_preview_code" value="<?php echo $applicationKey;?>"/>
<input type="hidden" name="app_code" value="<?php echo $applicationCode;?>"/>
<input type="hidden" name="selectedapp" value="mobilewebsite"/>
<input type="hidden" name="store_rooturl" value="<?php echo $storerooturl;?>"/>
</form>