<?php for($i=0;$i<intval($numberCopies);$i++): ?>
<div style="margin:5px; padding:5px; text-align: center; float:left; width: <?php echo $width ?>px; height: <?php echo $height ?>px; overflow: hidden;vertical-align: middle;<?php if($displayBorder=='1'): ?> border: 1px solid gray; <?php endif ?>">
  <span style="float: left; width: 100%; font-size: 12px; text-align: left; margin-left: 14px;"><?php echo $barcode->getProductName()?></span>
	<img width="<?php echo $width*0.9 ?>" height="<?php echo $height*0.7 ?>" src="<?php echo $this->getUrl('simibarcodeadmin/adminhtml_printbarcode/general',array('barcode_id'=>$barcode->getId())) ?>"/>
  <span style="float: left; text-align: center; width: 100%; font-size: 12px;"><?php echo $barcode->getBarcode()?></span>
</div>
<?php endfor; ?>