<html>
<head>
<SCRIPT LANGUAGE="JavaScript">
function fnSubmit() {

  window.document.payuForm.submit();
   return;
}
</SCRIPT>
<style>
#loader::after {
    bottom: 0;
    content: "Please Wait...";
    height: 40px;
    left: 0px;
    position: absolute;
    right: 0;
    text-align: center;
    top: 58%;
}
#loader {
    height: 100%;
    position: fixed;
    text-align: center;
    width: 100%;
}
#loader img {
    position: absolute;
    text-align: center;
    top: 50%;
}
#loader img {
    left: 50%;
    position: absolute;
    text-align: center;
    top: 50%;
    transform: translate(-50%, -50%);
}
</style>
</head>


<body LANGUAGE="javascript" onload="return fnSubmit()" >

<div id="loader">
  <img src="<?php echo $this->getSkinUrl('images/magentomobileshop/magentomobileshop_loader.gif') ?>"/>
</div>
<?php

$order_id = Mage::app()->getRequest()->getParam('orderid');

if(isset($order_id)):

      $order = Mage::getModel('sales/order')->loadByIncrementId($order_id);
      if (!$order->getId()):
        echo "<script type='text/javascript'>location.href ='".
          Mage::getBaseUrl()."payu/index/failure'</script>";
       
        exit;
      endif;

      $street = implode($order->getShippingAddress()->getStreet(),',');
      $contact = $order->getShippingAddress()->getTelephone();
      $city = $order->getShippingAddress()->getCity();
      $pincode = $order->getShippingAddress()->getPostcode();
      $lastname = $order->getShippingAddress()->getLastname();
      $Country = $order->getShippingAddress()->getCountry_id();
      $State = $order->getShippingAddress()->getRegion();

      $productinfo= $order->getShippingAddress()->getAddress_type();
       
      $MERCHANT_KEY = Mage::getStoreConfig('magentomobileshop_payment/payucheckout_shared/payu_key');
      $SALT = Mage::getStoreConfig('magentomobileshop_payment/payucheckout_shared/payu_salt');


      if(Mage::getStoreConfig('magentomobileshop_payment/payucheckout_shared/payu_mode')):
        $PAYU_BASE_URL = "https://secure.payu.in";
      else:
        $PAYU_BASE_URL = "https://test.payu.in";
      endif;

      $action = '';
      $posted = array();


      $posted['amount'] = $order->getBase_grand_total();
      $posted['firstname'] =  $order->getCustomer_firstname()?$order->getCustomer_firstname():$order->getBillingAddress()->getName();
      $posted['email'] = $order->getCustomer_email();
      $posted['phone'] = $order->getShippingAddress()->getTelephone();
      $posted['productinfo'] = $order_id;
      $posted['surl'] = $this->getUrl('payu/index/success');
      $posted['furl'] = $this->getUrl('payu/index/failure');
      $posted['service_provider'] = 'payu_paisa';
 $posted['txnid'] = $order_id;
  $posted['website'] = Mage::getBaseUrl();
      $posted['lastname']= $order->getShippingAddress()->getLastname();
      $posted['address1'] =  $street;
      $posted['address2'] =  $street;
      $posted['city'] =  $order->getShippingAddress()->getCity();
      $posted['state'] = $order->getShippingAddress()->getRegion();
      $posted['country'] = $order->getShippingAddress()->getCountry_id();
      $posted['zipcode'] = $order->getShippingAddress()->getPostcode();


        if(!empty($_POST)): 

          foreach($_POST as $key => $value):
                  $posted[$key] = $value; 
          endforeach;
        endif;

      $formError = 0;
      if(empty($posted['txnid'])):
         $txnid = substr(hash('sha256', mt_rand() . microtime()), 0, 20);
      else:
         $txnid = $posted['txnid'];
      endif;
      $hash = '';
     
      $hashSequence = "key|txnid|amount|productinfo|firstname|email|udf1|udf2|udf3|udf4|udf5|udf6|udf7|udf8|udf9|udf10";
      if(empty($posted['hash']) && sizeof($posted) > 0):
        
            if( empty($posted['key'])
                || empty($posted['txnid'])
                || empty($posted['amount'])
                || empty($posted['firstname'])
                || empty($posted['email'])
                || empty($posted['phone'])
                || empty($posted['productinfo'])
                || empty($posted['surl'])
                || empty($posted['furl'])
                || empty($posted['service_provider'])
            ):
                    $formError = 1;
            else:
                      
                        $hashVarsSeq = explode('|', $hashSequence);
                        $hash_string = '';  
                        foreach($hashVarsSeq as $hash_var):
                          $hash_string .= isset($posted[$hash_var]) ? $posted[$hash_var] : '';
                          $hash_string .= '|';
                        endforeach;

                        $hash_string .= $SALT;
                        $hash = strtolower(hash('sha512', $hash_string));
                        $action = $PAYU_BASE_URL . '/_payment.php';
            endif;
      elseif(!empty($posted['hash'])):
            $hash = $posted['hash'];
            $action = $PAYU_BASE_URL . '/_payment.php';
      endif;


?>


<div id="container" style="display: none;" >
<h2>PayU Form</h2>

<form action="<?php echo $action; ?>" method="post" name="payuForm">
  <input type="text" name="key" value="<?php echo $MERCHANT_KEY ?>" />
  <input type="text" name="hash" value="<?php echo $hash ?>"/>
  <input type="text" name="txnid" value="<?php echo $txnid ?>" />
  <table>
    <tr>
      <td><b>Mandatory Parameters</b></td>
    </tr>
    <tr>
      <td>Amount: </td>
      <td><input name="amount" value="<?php echo (empty($posted['amount'])) ? '' :  $posted['amount']; ?>" /></td>
      <td>First Name: </td>
      <td><input name="firstname" id="firstname" value="<?php echo (empty($posted['firstname'])) ? '' : $posted['firstname']; ?>" /></td>
    </tr>
    <tr>
      <td>Email: </td>
      <td><input name="email" id="email" value="<?php echo (empty($posted['email'])) ? '' : $posted['email']; ?>" /></td>
      <td>Phone: </td>
      <td><input name="phone" value="<?php echo (empty($posted['phone'])) ? '' : $posted['phone']; ?>" /></td>
    </tr>
    <tr>
      <td>Product Info: </td>
      <td colspan="3"><textarea name="productinfo"><?php echo (empty($posted['productinfo'])) ? '' : $posted['productinfo'] ?></textarea></td>
    </tr>
    <tr>
      <td>Success URI: </td>
      <td colspan="3"><input name="surl" value="<?php echo (empty($posted['surl'])) ? '' : $posted['surl'] ?>" size="64" /></td>
    </tr>
    <tr>
      <td>Failure URI: </td>
      <td colspan="3"><input name="furl" value="<?php echo (empty($posted['furl'])) ?     '' : $posted['furl'] ?>" size="64" /></td>
    </tr>

    <tr>
      <td>Service Provider: </td>
      <td colspan="3"><input name="service_provider" value="<?php echo (empty($posted['service_provider'])) ? '' : $posted['service_provider'] ?>" size="64" /></td>
    </tr>


<input name="service_provider" value="<?php echo (empty($posted['txnid'])) ? '' : $posted['txnid'] ?>" size="64" />
<input name="service_provider" value="<?php echo (empty($posted['website'])) ? '' : $posted['website'] ?>" size="64" />



    <tr>
      <td><b>Optional Parameters</b></td>
    </tr>
    <tr>
      <td>Last Name: </td>
      <td><input name="lastname" id="lastname" value="<?php echo (empty($posted['lastname'])) ? '' : $posted['lastname']; ?>" /></td>
      <td>Cancel URI: </td>
      <td><input name="curl" value="" /></td>
    </tr>
    <tr>
      <td>Address1: </td>
      <td><input name="address1" value="<?php echo (empty($posted['address1'])) ? '' : $posted['address1']; ?>" /></td>
      <td>Address2: </td>
      <td><input name="address2" value="<?php echo (empty($posted['address2'])) ? '' : $posted['address1']; ?>" /></td>
    </tr>
    <tr>
      <td>City: </td>
      <td><input name="city" value="<?php echo (empty($posted['city'])) ? '' : $posted['city']; ?>" /></td>
      <td>State: </td>
      <td><input name="state" value="<?php echo (empty($posted['state'])) ? '' : $posted['state']; ?>" /></td>
    </tr>
    <tr>
      <td>Country: </td>
      <td><input name="country" value="<?php echo (empty($posted['country'])) ? '' : $posted['country']; ?>" /></td>
      <td>Zipcode: </td>
      <td><input name="zipcode" value="<?php echo (empty($posted['zipcode'])) ? '' : $posted['zipcode']; ?>" /></td>
    </tr>
    <tr>
      <td>UDF1: </td>
      <td><input name="udf1" value="<?php echo (empty($posted['udf1'])) ? '' : $posted['udf1']; ?>" /></td>
      <td>UDF2: </td>
      <td><input name="udf2" value="<?php echo (empty($posted['udf2'])) ? '' : $posted['udf2']; ?>" /></td>
    </tr>
    <tr>
      <td>UDF3: </td>
      <td><input name="udf3" value="<?php echo (empty($posted['udf3'])) ? '' : $posted['udf3']; ?>" /></td>
      <td>UDF4: </td>
      <td><input name="udf4" value="<?php echo (empty($posted['udf4'])) ? '' : $posted['udf4']; ?>" /></td>
    </tr>
    <tr>
      <td>UDF5: </td>
      <td><input name="udf5" value="<?php echo (empty($posted['udf5'])) ? '' : $posted['udf5']; ?>" /></td>
      <td>PG: </td>
      <td><input name="pg" value="<?php echo (empty($posted['pg'])) ? '' : $posted['pg']; ?>" /></td>
    </tr>
    <tr>
      
        <td colspan="4"><input type="submit" value="Submit" /></td>
      
    </tr>
  </table>
</form>
</div>
</body>
</html>
<?php
else:
   echo "<script type='text/javascript'>location.href ='".
          Mage::getBaseUrl()."payu/index/failure'</script>";
   exit;
endif;
?>
