<?php $secure_key =    Mage::getStoreConfig('magentomobileshop/secure/key');
            $decode = base64_encode($secure_key);
 ?>
<script>
 function showResult()
{
     window.location.href = 'https://www.magentomobileshop.com/user/activating-app?app=<?php echo $decode; ?>';
    // window.location.href = 'http://mastersoftwaretechnologies.com/magentomobilecart/user/activating-app?app=<?php echo $decode; ?>';
                        

}
    </script>
               

    <div class="container inner-container">
        <div class="row">
        <?php// $test = $_REQUEST; ?>
              <span style="cursor:pointer;">
              <img src="<?php echo $this->getSkinUrl('images/magentomobileshop/magento_logo.png')?>" width="350" height="145" />

             <?php // if($test) {  ?>
              <form id="support"  role="form" class="smart-green">
                    <h1 align="center" onclick="showResult();">Click here to activate  your extension
                    </h1>
              </form> 
              </span>
              <?php// } ?>
         
        </div>
    </div>

<style>

.container.inner-container {
  box-shadow: 0 0 3px #e4e4e4;
  margin: 20px auto 0;
  padding: 30px 20px 20px 20px;
  text-align: center;
  width: 40%;
}
.container.inner-container img {
    height: auto;
    width: 270px;
}
.container.inner-container h1 {
    border-radius: 0;
    box-shadow: none;
    font-size: 16px;
    margin: 0;
    padding: 14px 45px;
    text-shadow: none;
}
.container.inner-container form.smart-green {
    display: inline-block;
    margin-top: 0;
}







.smart-green {
    margin-left:auto;
    margin-right:auto;

    max-width: 100%;
    /*background: #F8F8F8;*/
    padding: 30px 30px 20px 30px;
    font: 12px Arial, Helvetica, sans-serif;
    color: #666;
    border-radius: 5px;
    -webkit-border-radius: 5px;
    -moz-border-radius: 5px;
}
.smart-green h1 {
    font: 24px "Trebuchet MS", Arial, Helvetica, sans-serif;
    padding: 20px 0px 20px 40px;
    display: block;
    margin: -30px -30px 10px -30px;
    color: #FFF;
    background: #9DC45F;
    text-shadow: 1px 1px 1px #949494;
    border-radius: 5px 5px 0px 0px;
    -webkit-border-radius: 5px 5px 0px 0px;
    -moz-border-radius: 5px 5px 0px 0px;
    border-bottom:1px solid #89AF4C;

}
.smart-green h1>span {
    display: block;
    font-size: 11px;
    color: #FFF;
}

.smart-green label {
    display: block;
    margin: 0px 0px 5px;
}
.smart-green label>span {
    float: left;
    margin-top: 10px;
    color: #5E5E5E;
}
.smart-green input[type="text"], .smart-green input[type="email"], .smart-green textarea, .smart-green select {
    color: #555;
    height: 30px;
    line-height:15px;
    width: 100%;
    padding: 0px 0px 0px 10px;
    margin-top: 2px;
    border: 1px solid #E5E5E5;
    background: #FBFBFB;
    outline: 0;
    -webkit-box-shadow: inset 1px 1px 2px rgba(238, 238, 238, 0.2);
    box-shadow: inset 1px 1px 2px rgba(238, 238, 238, 0.2);
    font: normal 14px/14px Arial, Helvetica, sans-serif;
}
.smart-green textarea{
    height:100px;
    padding-top: 10px;
}
.smart-green select {
    background: url('down-arrow.png') no-repeat right, -moz-linear-gradient(top, #FBFBFB 0%, #E9E9E9 100%);
    background: url('down-arrow.png') no-repeat right, -webkit-gradient(linear, left top, left bottom, color-stop(0%,#FBFBFB), color-stop(100%,#E9E9E9));
   appearance:none;
    -webkit-appearance:none;
   -moz-appearance: none;
    text-indent: 0.01px;
    text-overflow: '';
    width:100%;
    height:30px;
}
.smart-green .button {
    background-color: #9DC45F;
    border-radius: 5px;
    -webkit-border-radius: 5px;
    -moz-border-border-radius: 5px;
    border: none;
    padding: 10px 25px 10px 25px;
    color: #FFF;
    text-shadow: 1px 1px 1px #949494;
}
.smart-green .button:hover {
    background-color:#80A24A;
}
/*sUPPORT FORM CSS START HERE */
</style>
