<script>
/**
	- showResult : Function used to send data useing Ajax hit.
	- Data send to Support controller and method is supportmailAction
	- Path : support controller (/app/code/local/Mss/Connector/controllers/Adminhtml/SupportController.php)

*/
		
function showResult()
{
	var subject = document.getElementById("subject").value;
	var email  = document.getElementById("email").value;

	var emailRegEx = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;

	str = email;
	//email validation
	if(!str.match(emailRegEx)){
		alert('Please enter a valid email address.');
		return false;

	}


	var message  = document.getElementById("message").value;
	var url = '<?php echo Mage::helper("adminhtml")->getUrl("admin_support/adminhtml_support/supportmail"); ?>';

	if(!email || !subject || !message) {
		alert('All fields are required.');
		return;
	}

	new Ajax.Request(url, {
		method:'get',
		parameters: {'message':message,'email':email,'subject':subject},
		onSuccess: function(response) {	
				
	var response = JSON.stringify(response.responseText);
	var data = JSON.parse(response);				
		
			 document.getElementById("information").innerHTML = data;
		},
		onFailure: function(response) { 
			
			  var response = response.responseText					
			 document.getElementById("information").innerHTML = response;

		}
	});			
}
</script>

<!-- MagentoMobileShop Email from start here -->
		
			  <form id="support"  role="form" class="smart-green">
			  		<h1>Any Problem?
				        <span>Contact Us...</span>
				    </h1>
				     <p id="information" align="center" style="color:#469DF0; font-family:verdana;font-size:16px;">				     	
				     </p> 
				    <label>
				        <span>Your Email :</span>
				        <input id="email" type="email" name="email" placeholder="Valid Email Address" required/>
				    </label>
				    <label>
				        <span>Your Subject :</span>
				        <input id="subject" type="text" name="subject" placeholder="Enter subject" required/>
				    </label>
				   
				    <label>
				        <span>Message :</span>
				        <textarea id="message" name="message" placeholder="Your Message to Us"></textarea>
				    </label>
				    <label>
      				  <span>&nbsp;</span>
				     <input  style="width:140px;height:35px" class="button" type="button" value="Send Email" onclick="showResult();"/> 
				     </label>
				</form>	

<!-- MagentoMobileShop Email from end here -->

<style>
/*sUPPORT FORM CSS START HERE */

.smart-green {
    margin-left:auto;
    margin-right:auto;

    max-width: 100%;
    /*background: #F8F8F8;*/
    padding: 30px 30px 20px 30px;
    font: 12px Arial, Helvetica, sans-serif;
    color: #666;
    border-radius: 5px;
    -webkit-border-radius: 5px;
    -moz-border-radius: 5px;
}
.smart-green h1 {
    font: 24px "Trebuchet MS", Arial, Helvetica, sans-serif;
    padding: 20px 0px 20px 40px;
    display: block;
    margin: -30px -30px 10px -30px;
    color: #FFF;
    background: #9DC45F;
    text-shadow: 1px 1px 1px #949494;
    border-radius: 5px 5px 0px 0px;
    -webkit-border-radius: 5px 5px 0px 0px;
    -moz-border-radius: 5px 5px 0px 0px;
    border-bottom:1px solid #89AF4C;

}
.smart-green h1>span {
    display: block;
    font-size: 11px;
    color: #FFF;
}

.smart-green label {
    display: block;
    margin: 0px 0px 5px;
}
.smart-green label>span {
    float: left;
    margin-top: 10px;
    color: #5E5E5E;
}
.smart-green input[type="text"], .smart-green input[type="email"], .smart-green textarea, .smart-green select {
    color: #555;
    height: 30px;
    line-height:15px;
    width: 100%;
    padding: 0px 0px 0px 10px;
    margin-top: 2px;
    border: 1px solid #E5E5E5;
    background: #FBFBFB;
    outline: 0;
    -webkit-box-shadow: inset 1px 1px 2px rgba(238, 238, 238, 0.2);
    box-shadow: inset 1px 1px 2px rgba(238, 238, 238, 0.2);
    font: normal 14px/14px Arial, Helvetica, sans-serif;
}
.smart-green textarea{
    height:100px;
    padding-top: 10px;
}
.smart-green select {
    background: url('down-arrow.png') no-repeat right, -moz-linear-gradient(top, #FBFBFB 0%, #E9E9E9 100%);
    background: url('down-arrow.png') no-repeat right, -webkit-gradient(linear, left top, left bottom, color-stop(0%,#FBFBFB), color-stop(100%,#E9E9E9));
   appearance:none;
    -webkit-appearance:none;
   -moz-appearance: none;
    text-indent: 0.01px;
    text-overflow: '';
    width:100%;
    height:30px;
}
.smart-green .button {
    background-color: #9DC45F;
    border-radius: 5px;
    -webkit-border-radius: 5px;
    -moz-border-border-radius: 5px;
    border: none;
    padding: 10px 25px 10px 25px;
    color: #FFF;
    text-shadow: 1px 1px 1px #949494;
}
.smart-green .button:hover {
    background-color:#80A24A;
}
/*sUPPORT FORM CSS START HERE */
</style>
