<?php $product = Mage::getModel('catalog/product')->load($barcode->getProductEntityId());?>
<?php for($i=0;$i<intval($numberCopies);$i++): ?>
<div style="margin:5px; padding:5px; text-align: center; float:left; width: <?php echo $width ?>px; height: <?php echo $height ?>px; overflow: hidden;vertical-align: middle;<?php if($displayBorder=='1'): ?> border: 1px solid gray; <?php endif ?>">
  <span style="float: left; font-size: 12px; text-align: left; width: 47%; margin-left: 13px;"><?php echo $product->getName()?></span>
  <span style="font-size: 17px; float: left; text-align: left; margin-left: 55px; width: 20%;"><?php echo Mage::helper('core')->currency($product->getPrice())?></span>
	<img width="<?php echo $width*0.9 ?>" height="<?php echo $height*0.6 ?>" src="<?php echo $this->getUrl('simibarcodeadmin/adminhtml_printbarcode/general',array('barcode_id'=>$barcode->getId())) ?>"/>
  <span style="float: left; text-align: center; width: 100%; font-size: 17px;"><?php echo $barcode->getQrcode()?></span>
</div>
<?php endfor; ?>